### PR TITLE
Add Beam Background Filter and QA Module

### PR DESCRIPTION
**Pull request by ruse-traveler**
This PR introduces the `BeamBackgroundFilterAndQA` module, a module to flag events as having beam background and (if specified) QA them.

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This PR introduces new functionality: a module which consolidates various algorithms ("filters") to identify events which may contain beam background. The module is designed in such a way as to allow for additional filters to be added with relatively minimal boilerplate.

The outcome of each filter -- as well as the overall result -- are stored as `PHFlag`s in the `recoConsts` database which can be retrieved in downstream modules. There is also the option to discard events in which a filter identifies beam background.

This module also keeps histograms various quantities associated with each filter such as how many events were flagged as having beam background by a specific filter. If QA mode is on (`.doQA = true`), these will be picked up by the QA Histogram Manager.

## Links to other PRs in macros and calibration repositories (if applicable)

Additional documentation as well as an example of how to use the module in a macro and how to access the result flags in downstream modules is available in the module's repository in [sPHENIX-Collaboration/analysis](https://github.com/sPHENIX-Collaboration/analysis/tree/master/JS-Jet/BeamBackgroundFilterAndQA).

### CODE REVIEW

**Comment by ruse-traveler** [comment]
I think this is ready for review, but there are 2 questions I'd appreciate some guidance on:
1. I placed the module in the `jetbackground` package since this deals with background, but I could also see this belonging in the `JetQA` package since it has (some) QA functionality. Is there any preference?
2. And it's not completely clear to me how to flag an event as simply "interesting" other than to just abort i, is there a way for this module to somehow flag an event for downstream modules to analyze?

The 2nd question is motivated by the JS TG: initially the module was written to just abort an event once beam background was identified, but the TG requested a way to retain events with background for further analysis.

Currently, the user can toggle the abort behavior on/off, but I was wondering if there was a way to actually flag an event so that downstream modules know the event had something in it.

**Comment by ruse-traveler** [comment]
@Hanpu-Jiang @njapplegate let me know if you any have feedback!

**Comment by pinkenburg** [comment]
> I think this is ready for review, but there are 2 questions I'd appreciate some guidance on:
> 
>     1. I placed the module in the `jetbackground` package since this deals with background, but I could also see this belonging in the `JetQA` package since it has (some) QA functionality. Is there any preference?
> 
>     2. And it's not completely clear to me how to flag an event as simply "interesting" other than to just abort i, is there a way for this module to somehow flag an event for downstream modules to analyze?
> 
> 
> The 2nd question is motivated by the JS TG: initially the module was written to just abort an event once beam background was identified, but the TG requested a way to retain events with background for further analysis.
> 
> Currently, the user can toggle the abort behavior on/off, but I was wondering if there was a way to actually flag an event so that downstream modules know the event had something in it.

There is no provision for this (yet). A module can steer which events get written out by an attached output managers but that channel doesn't exist between modules. We can use PHFlags for this which are globally accessible for the time being

**Comment by ruse-traveler** [comment]
Just pushed changes to (1) fix the clang/cpp-check errors, and (2) to store the results of each filters as flags in `recoConst`. There's an example of how to retrieve these in a downstream module in the analysis repo linked to in the PR description.

**Pull request merged**
