### PR TITLE
Add Strange Lambdas to Resonance Jet Tagger

### PR DESCRIPTION
**Pull request by ruse-traveler**
[comment]: This PR extends the functionality of the `ResonanceJetTagging` module to enable the tagging of jets with strange lambdas.

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: this PR adds a new feature and does not introduce any breaking changes downstream.

## TODOs (if applicable)

[comment]: n/a ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

[comment]: n/a

### CODE REVIEW

**Comment by pinkenburg** [comment]
Don't worry about the scan build failure - it's a false positive and in addition not your problem. Once it's added to the known errors it will vanish

**Comment by ruse-traveler** [comment]
> Don't worry about the scan build failure - it's a false positive and in addition not your problem. Once it's added to the known errors it will vanish

Phew! 😌

**Comment by ruse-traveler** [comment]
BTW I'm leaving this in a draft state until we run a few tests to confirm it does what I expect it to...

**Comment by antoniocosilva** [comment]
> c.c. @antoniocosilva: if you're okay with it, should we go ahead and merge this? (Assuming it passes Jenkins...)

Hi Derek. Yes, looks good!

**Pull request merged**
