### PR TITLE
Fix proj crystal calorimeter

### PR DESCRIPTION
**Pull request by nfeege**
Remove shadowed variables pointed out in issue https://github.com/sPHENIX-Collaboration/coresoftware/issues/102

### CODE REVIEW

**Comment by blackcathj** [comment]
Hi @nfeege 

Thank you for looking into this problem. 

Meanwhile, I do have one comment: At this moment, 12 interface functions in PHG4ProjCrystalCalorimeterDetector still shadows those from PHG4CrystalCalorimeterDetector, e.g. PHG4ProjCrystalCalorimeterDetector::SetPlace() shadows PHG4CrystalCalorimeterDetector::SetPlace(). It is OK for get things running, but could be confusing in future because it is tricky for user to find whether SetPlace() is called in which of the two classes. 

A minor change to solve this confusion could be base PHG4ProjCrystalCalorimeterDetector on PHG4Detector, rather than on PHG4CrystalCalorimeterDetector. It looks one line change to me, but I could missed some additional connection between the two classes.

**Comment by nfeege** [comment]
Hi @blackcathj ,

I mainly used the inheritance to make the selection of 'projective' or 'non-projective' version work in PHG4CrystalCalorimeterSubsystem.cc (lines 40 - 48, https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc).

Do you have a better suggestion of how to do that without the inheritance? If yes, I'd be glad to remove it.

**Comment by pinkenburg** [comment]
I would say to go with Mikes suggestion (which should also be 
implemented where I used protected variables like in our single particle 
generators). If you inherit from a class, make the data members of the 
parent private (not protected) so they are not shared with the derived 
classes. Then use the public methods of the parent class (if you want to 
make sure they are only accessible by the derived classes make those 
protected) to access those variables. As a concrete example in your 
projective implementation which inherits from the 
PHG4CrystalCalorimeterSubsystem class, just remove the SetPlace() method 
(and the associated variables). Then it will use the method from the 
parent. To access the variable which is now private in the parent class 
use the public/protected access method.

I thought of using something similar for the outer and inner hcal which 
do have a large overlap but then wanted the flexibility to change things 
without impacting the other hcal. I still might revisit this once things 
have settled down

Chris


On 1/12/2016 10:25 AM, Nils Feege wrote:
>
> Hi @blackcathj <https://github.com/blackcathj> ,
>
> I mainly used the inheritance to make the selection of 'projective' or 
> 'non-projective' version work in PHG4CrystalCalorimeterSubsystem.cc 
> (lines 40 - 48, 
> https://github.com/sPHENIX-Collaboration/coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc).
>
> Do you have a better suggestion of how to do that without the 
> inheritance? If yes, I'd be glad to remove it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sPHENIX-Collaboration/coresoftware/pull/103#issuecomment-170946324>.
>

-- 
*************************************************************

Christopher H. Pinkenburg	;    pinkenburg@bnl.gov
				;    http://www.phenix.bnl.gov/~pinkenbu

Brookhaven National Laboratory	;    phone: (631) 344-5692
Physics Department Bldg 510 C	;    fax:   (631) 344-3253
Upton, NY 11973-5000

*************************************************************

**Comment by nfeege** [comment]
Thanks for the details, I'll implement this today for the CrystalCalorimeter.

**Comment by nfeege** [comment]
@blackcathj I think I fixed the remaining issues.

**Comment by blackcathj** [comment]
As discussed in the last meeting, we will merge once this problem is fixed. And the current version satisfied both GCC and CPPCHECK. And no more shadowing of function or variable. Merging.

**Pull request merged**
