### PR TITLE
Added InttDeadMap and InttSurveyMap classes, removed unused source files (more cleanup eventually once other files become properly phased out)

### PR DESCRIPTION
**Pull request by josephbertaux**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
I applied clang-tidy, clang-format to align this code with our coding conventions and rearranged the includes using clangs include what you use tool.
clang-tidy found one possible issue which needs resolving before this PR can be okayed:
In CylinderGeomIntt a method
void find_strip_center_localcoords(const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[]);
is declared which does look like a typo. PI left it as is - please check and correct if clang-tidy is correct

**Comment by josephbertaux** [comment]
Thanks for applying those. I haven't touched the CylinderGeometry--do you know who might've been the last to work on it/use it? I can see a full implementation in the .cc and it looks like it computes and assigns something to the passed array `double location[]`

I don't think it's called by any other CylinderGeomIntt member functions, but it seems useful and I'm in favor of leaving it. I'll ask Takashi about it.

**Comment by josephbertaux** [comment]
Takashi hasn't changed that file recently, either, and is in favor of keeping it. If I need to edit the code to get clang-tidy to accept it, let me know

**Comment by josephbertaux** [comment]
Found the output about that method in the clang-tidy ouput file (https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/clang-tidy-pipeline/77//artifact/clang-tidy-result.txt/*view*/), looks like jenkins thinks it should be an override
```
/var/lib/jenkins/workspace/sPHENIX/clang-tidy-pipeline@4/coresoftware/offline/packages/intt/CylinderGeomIntt.cc:237:1: warning: method 'CylinderGeomIntt::find_strip_center_localcoords' has a similar name and the same signature as virtual method 'PHG4CylinderGeom::find_strip_center_local_coords'; did you mean to override it? [bugprone-virtual-near-miss]
void CylinderGeomIntt::find_strip_center_localcoords(const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
```
There are some other benign things, too, but doing a Ctrl+F on the output with `/intt/` (for files in that subdir) only gives 10 results, and they're all warnings.

Would you mind adding `override` to the declaration? I'm worried if I push commits after your clang-tidy, there will be conflicts (unless I can pull those commits from your branch)

**Pull request merged**
