### PR TITLE
change to cluster v4. For real this time

### PR DESCRIPTION
**Pull request by bogui56**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
@pinkenburg This should not have been merged, it kills the momentum resolution. Once the issues from this PR get sorted out we can reset the QA

**Comment by osbornjd** [comment]
Apparently PR [1591](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1591#event-7064864761) fixes most of this, but we really need to get the QA back in business because we are degrading things that we don't entirely understand

**Comment by sPHENIX-GitHub-l** [comment]
the follow up pull request that restores the momentum resolution is out.
The followup also adds back the QA mods and the TrackEvaluation. 

Once jenkins is through with this, lets look at it and merge that one and we should be ok.

**Comment by sPHENIX-GitHub-l** [comment]
ah, looks like this one also got merged faster than I expected. 
Let me issue another pull request to get the QA and TrackEval in.

**Pull request merged**
