### PR TITLE
(subsystems/intt) Added functionality to retrieve GL1 file names in the InttOdbcQuery class

### PR DESCRIPTION
**Pull request by josephbertaux**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by josephbertaux** [comment]
Marking as "ready for review" from "draft"
Sorry for the multiple build triggers--there were some niceties I was tempted to put off for another PR but ended up implementing in this one

**Comment by pinkenburg** [comment]
The search query will time out. It tries a match on millions of entries. Our replicas don't handle long request to be able to survive the onslaught by 200k jobs

**Comment by josephbertaux** [comment]
Can it be fixed by modifying the query, by using a nested one like

SELECT ... FROM (SELECT ... FROM filelist WHERE runnumber = ...) WHERE filename LIKE ...?


________________________________

**Comment by josephbertaux** [comment]
I think not. Could it be solved by maintaining sections of this information in smaller tables for runnumber ranges, similar to how we have subdirectories for the production DST files?

**Comment by pinkenburg** [comment]
The daq DB is just the wrong place to look this up. The field if a file is on disk or not is not kept up to date. What you see is the state when the file was transferred. If a file gets removed or staged from tape the daq DB does not reflect this. The production hands down lists of files (with full path or filename which then gets looked up in our file catalog), there is no need to have this functionality in our code. We need a catalog for the raw data files which then reflects what is on disk and in hpss, but creating this is currently somewhat lower priority since the production can do without.

**Pull request closed without merging**
