### PR TITLE
read from cdb if file is available

### PR DESCRIPTION
**Pull request by osbornjd**
Read the fieldmap from the CDB if it is available, per Chris' suggestion.

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
That crash is a bug in the code. The CDB returns a fully qualified path, but the code prepends it with the path to $CALIBRATIONSROOT:
 char *calibrationsroot = getenv("CALIBRATIONROOT");
      m_magField = "sphenix3dtrackingmapxyz.root";
      
      m_magField = CDBInterface::instance()->getUrl("FIELDMAPTRACKING");
    
      if (calibrationsroot != nullptr)
      {
	m_magField = std::string(calibrationsroot) + std::string("/Field/Map/") + m_magField;
      }
That then results in
 /var/lib/jenkins/workspace/sPHENIX/Build-Master-gcc12@4/build/new/install.1/share/calibrations/Field/Map//cvmfs/sphenix.sdcc.bnl.gov/calibrations/sphnxpro/cdb/FIELDMAPTRACKING/8e/4d/8e4d6c3b1660540a658da3a275af2bde_sphenix3dtrackingmapxyz.root
being handed down as fieldmap. It look like MakeActsGeometry() then throws an exception if the file is not found

**Comment by osbornjd** [comment]
Actually, we're not  going away from the CDB so is there any reason to leave the calibrations root stuff in there and not just read from the CDB by default?

**Comment by pinkenburg** [comment]
That would be fine by me. I think initially there was an idea to keep the ability to run without cdb in some containers but we should cut that cord. Otherwise we just have backdoors which can bite us

**Comment by osbornjd** [comment]
Ah I see, that makes sense, as I think I recall the singularity container doesn't have access to the CDB. I can leave it in just as a backup.

**Pull request merged**
