### PR TITLE
New TPC gas mixture simulation code

### PR DESCRIPTION
**Pull request by cdean-github**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

In anticipation of isobutane, I altered the TPC gas mixture in simulation so we can tune the components (argon, CF4, nitrogen and isobutane) and conditions (temperature, pressure) from the macro level. If we can interface this with CDB info on all these parameters, we should be able to set the gas parameters run-by-run

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
The first valgrind error is known (but without traceback impossible to locate). The second valgrind error is know, it pipes up because of a shifted line, not a problem

**Comment by osbornjd** [comment]
According to the QA somehow the clusters become smaller (?)
https://nbviewer.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-low-occupancy-qa-5780-test-tracking_Event500_Sum30/QA-Tpc.ipynb

That would explain the smaller cluster uncertainties and thus the large growth of the momentum resolution we saw this morning

**Comment by osbornjd** [comment]
This appears even to be true with the macro changes
https://nbviewer.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-pythiajet-qa-4103-test-tracking_Event550_Sum10/QA-Tpc.ipynb

**Comment by cdean-github** [comment]
> This appears even to be true with the macro changes https://nbviewer.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-pythiajet-qa-4103-test-tracking_Event550_Sum10/QA-Tpc.ipynb

OK, so sounds like there could be an error in the code somewhere

**Comment by cdean-github** [comment]
> According to the QA somehow the clusters become smaller (?) https://nbviewer.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-low-occupancy-qa-5780-test-tracking_Event500_Sum30/QA-Tpc.ipynb
> 
> That would explain the smaller cluster uncertainties and thus the large growth of the momentum resolution we saw this morning

Would this be a cause for the smaller clusters? The QA reference should have used the earlier values (0.085 and 0.105)
```c++
  set_default_double_param("added_smear_trans", 0.0);  // cm (used to be 0.085 before sims got better)
  set_default_double_param("added_smear_long", 0.0);   // cm (used to be 0.105 before sims got better)
  ```

**Comment by adfrawley** [comment]
When I set the added smear parameters to zero with the ArCF4 gas, the momentum resolution improved. This was expected, those parameters were put in when our simulations were less realistic to allow for things that were not done correctly.

The increased diffusion of the isobutane gas mixture should have compensated for setting the additional smear to zero.

Tony


________________________________

**Pull request merged**
