### PR TITLE
YCM possible trick to remove memory leak and make valgrind happy

### PR DESCRIPTION
**Pull request by ycorrales**
[comment]: <> (Please tell us something about this pull request)
This PR is just a test to remove valgrind complains in g4micromegas
## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
handing down the address of a local G4RotationMatrix does not work. It goes out of scope and the rotation during the actual detector construction is done using garbage values

**Comment by ycorrales** [comment]
Very strange, we I used some similar approach for assembly volume and it works. Actually a possible solution is using a G4Tranform3D as in https://github.com/sPHENIX-Collaboration/coresoftware/blob/b51c2947ac504b1d419524c0fb36d0eeda269401/simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc#L197

**Comment by hupereir** [comment]
Yasser, 
using G4Transform3D would fix it indeed. What G4VPlacement does in that case is that it creates the rotation internally, and takes care of deleting it, when the placement gets out of scope, I think.
 The only drawback is that one creates a new rotation for each placement, instead of having the possibility to reuse the same rotation.
This should not be a problem in our case. 
I'll switch to this construct and we will see.

**Comment by hupereir** [comment]
see e.g. https://apc.u-paris.fr/~franco/g4doxy/html/classG4PVPlacement.html

**Comment by ycorrales** [comment]
yes, you are right

**Pull request closed without merging**
