### PR TITLE
add base class functions

### PR DESCRIPTION
**Pull request by osbornjd**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This PR adds some functions to the TrkrCluster base class which are in v5 but not in the base class currently. Having this will prevent any casting gymnastics to occur

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
@pinkenburg I just want to make sure before merging this that these changes will not affect our DST readback capabilities.

**Review by pinkenburg — APPROVED** [review]
looks good - shouldn't cause problems (but anyone not recompiling their own code will see very interesting behavior)

**Comment by hupereir** [comment]
@osbornjd 
Maybe before merging, I noticed that the TrkrClusterv5::CopyFrom method is very incomplete
I does not include copying any of the new members of the class (mostly because there was no base class accessors !)
Can you add them ? Alternatively I can do that quickly in a separate PR

**Comment by osbornjd** [comment]
Thanks for pointing it out, I will add them to this PR since it is trying to clean up some of the derived classes

**Comment by hupereir** [comment]
Also, the TrkrClusterv5::CopyFrom( TrkrClusterv5* source) method should go
It is irrelevant if the copyFrom( base class) is complete.

**Comment by hupereir** [comment]
And I just noticed that the same is true for Clusterv4.
This is really a mess. We should pay more attention when increasing versions

**Comment by osbornjd** [comment]
> Also, the TrkrClusterv5::CopyFrom( TrkrClusterv5* source) method should go It is irrelevant if the copyFrom( base class) is complete.

can you elaborate on this point? The base class implementation is just a blank empty function. Shouldn't this mean it should be left in?

**Comment by hupereir** [comment]
> 

What I mean is that TrkrClusterv5::CopyFrom( TrkrCluster* ) should be enough
If you call all the base class methods in there, it will copy the right thing if what is passed as argument is actually a TrkrClusterv5, and thus will do the exact same thing as TrkrClusterv5::CopyFrom( TrkrClusterv5* )
(and it will also work for v6, v7, etc)
So the second method is superfluous, once the first one is fixed. 
Makes sense ?

**Comment by osbornjd** [comment]
> 

I'm assuming one of those was supposed to be a `CopyFrom(const TrkrCluster&)` rather than `CopyFrom(TrkrCluster*)`. But I think I get the main point, basically they do the same thing

**Comment by osbornjd** [comment]
@hupereir let me know if the last commit addresses all your points, I think it does.

**Comment by hupereir** [comment]
> @hupereir let me know if the last commit addresses all your points, I think it does.

Looks good yes ! (as far as I can tell). Thanks !

**Pull request merged**
