### PR TITLE
add proper dynamic cast to use cluster v5

### PR DESCRIPTION
**Pull request by bogui56**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by hupereir** [comment]
I am confused. Why is it necessary at all  ? getRPhiError and getZError are virtual methods from the base class. There should be no need to cast to the latest version. Or did the signature change for ClusterV5 ? 
This code will crash if one runs the tracking on a DST with clustersV4.
IMHO it should be better to investigate why the called method does not follow inheritance (assuming this is really the issue).

**Comment by bogui56** [comment]
I am confused too, but in the latest build the getRPhiError just printed the error message you get from calling the base class method
instead of returning the implemented method from clusterv5.

If you know another way around this let me know.

Cheers

   Christof

**Comment by osbornjd** [comment]
Tony found instances where there was not an if statement in the code for clusterv5 and thus the clusterv4 was being called, leading to seg faults or other undefined behavior. I think as a general statement we need to consider how this is going to work long term because it is not feasible to have a block of code like
```
if(clusterv3)
{ do something }
else if(clusterv4)
{ do something else}
else if (clusterv5)
{ do a third thing }
else if(clusterv6)
{ do a fourth thing}
...
```

in every module that needs the clusters, which is a lot of them. This just isn't scalable in the long term

**Comment by bogui56** [comment]
Hi Joe, 

I agree. in the beginning this was supposed to be a tempory solution to try the perforrmance with a cluster object that has a reduced set 
of data members. Maybe its time to think about a more permanent solution. Any suggestions are more than welcome. 

Regarding the pull request adding the dynamic cast I am still confused. The situation of the getRPhiError throwing the error message 
from the base class instead of returning the cluster error from clusterv5 looks to have been temporary. The default behaviour has changed again 
today. No clue what caused this. I will withdraw the pull request.

cheers

   Christof

**Comment by hupereir** [comment]
> Tony found instances where there was not an if statement in the code for clusterv5 and thus the clusterv4 was being called, leading to seg faults or other undefined behavior. I think as a general statement we need to consider how this is going to work long term because it is not feasible to have a block of code like
> 
> ```
> if(clusterv3)
> { do something }
> else if(clusterv4)
> { do something else}
> else if (clusterv5)
> { do a third thing }
> else if(clusterv6)
> { do a fourth thing}
> ...
> ```
> 
> in every module that needs the clusters, which is a lot of them. This just isn't scalable in the long term

In principle that's exactly what virtual functions are supposed to do for you, so maybe we should revisit where these switches happen and encapsulate that into virtual functions from TrkrCluster with different implementations for each function. I might be able to have a look next week.

**Comment by bogui56** [comment]
For the most part we can do this with virtual functions, except for v4 where we simply dont store the error is the cluster struct. 
We could make v4 return a nan with getRPhiError and catch it and replace it with the ClusterErrorPara. But that is also not a clean solution.

Lets discuss this in the next tracking or simsoft meeting

Cheers

  Christof

**Pull request closed without merging**
