### PR TITLE
sfl - added MBD and ZDC QA plots

### PR DESCRIPTION
**Pull request by samfred72**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by samfred72** [comment]
A module for creating histograms for ZDC and MBD QA

**Comment by osbornjd** [comment]
I sent you an invitation to join - please accept it and then after you do that do a 
```
git commit --allow-empty -m "trigger jenkins"
git push fork devGlobalQA
```

**Comment by osbornjd** [comment]
clang-tidy error does not have to do with this

**Review by osbornjd — CHANGES_REQUESTED** [review]
Can you make the names of the histograms something like`h_GlobalQA_histo_name`, as I assume this will probably get included with the calo qa and we want to be able to know what module produces what histograms. Also please remove the calls to the histomanager that aren't used (e.g. in process_event)

**Pull request merged**
