### PR TITLE
KFParticle

### PR DESCRIPTION
**Pull request by cdean-github**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people) (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )
This is the initial push of the KFParticle project for event reconstruction at sPHENIX.

The project was initially developed in the analysis repository before this move to core software. clang-format and cppcheck have previously been run so hopefully there isn't too much work to be done after jenkins runs over this. The corresponding software meeting link for this project is https://indico.bnl.gov/event/7445/

KFParticle was developed outside sPHENIX and the base code is not maintained by us. This project is effectively a wrapper for Fun4All and uses KFParticle object to perform a more generic event reconstruction. The main features of the project are:

(1) Variable input sources - The project translates SvtxTrack's and SvtxVertex's into KFParticle objects but the node used can be specified by the user at configuration. If different input styles are needed then a short function to extract and trranslate the style must be produced.

(2) General event reconstruction - The user configures the reconstruction style (all final state tracks, all intermediate states or a mix of the two) and some selctions commonly used in high energy (nuclear) physics analysis. KFParticle then searches your input files for anything matching this selection.

(3) Output written directly to an nTuple or objects placed back on node tree - The user can specify to save their selection to an nTuple with one boolean option. The package then takes care of creating a sensible output file for you, no need to specify branches or names (except to enable truth matching or detector info). Similarly, the user can specify whether the candidates should be appended back to the node tree with one boolean option as an SvtxTrack and/or KFParticle container. The new SvtxTrackMap will also contain the reconstructed particles like J/psi or Lambda_c, interpreted as a track

Example macros can still be found in the analysis repository. A G4 macro for the macros repo will be developed soon.

This is a draft PR to be tested by Jenkins before a full merge and should only exist on my own KFParticle branch

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for run checks using Jenkins, please add the Label `preview-do-not-merge` on the right column  )

I need to test the MVA calculation in KFParticle. Some algorithm must be trained first so this will probably happen soon after MDC-1 when we have background samples to train on
I need to make a G4 macro so we can use KFParticle in our more general testing/user framework

### CODE REVIEW

**Comment by cdean-github** [comment]
I don't seem to be able to add a label to this PR. Looking on google it seems to indicate this is reserved for people with write access. I've set this PR to work-in-progress, hopefully this doesn't cause too many issues. The build robot seems to be doing its thing though

**Comment by pinkenburg** [comment]
Don't worry about this - I am currently going through the code and am fixing these issues

**Comment by cdean-github** [comment]
Hi Chris,

Thanks, I’m actually doing the same here and have suppressed the messages on my side, I’m going through the specific ones Jenkins picked up.

Cheers,
Cameron

cppcheck --enable=all --std=c++17 --language=c++ KFParticle_*
Checking KFParticle_Container.cc ...
1/18 files checked 2% done
Checking KFParticle_Container.h ...
2/18 files checked 3% done
Checking KFParticle_DST.cc ...
3/18 files checked 10% done
Checking KFParticle_DST.h ...
4/18 files checked 12% done
Checking KFParticle_MVA.cc ...
5/18 files checked 13% done
Checking KFParticle_MVA.h ...
6/18 files checked 13% done
Checking KFParticle_Tools.cc ...
7/18 files checked 30% done
Checking KFParticle_Tools.h ...
8/18 files checked 34% done
Checking KFParticle_eventReconstruction.cc ...
9/18 files checked 48% done
Checking KFParticle_eventReconstruction.h ...
10/18 files checked 51% done
Checking KFParticle_nTuple.cc ...
11/18 files checked 69% done
Checking KFParticle_nTuple.h ...
12/18 files checked 74% done
Checking KFParticle_particleList.cc ...
13/18 files checked 80% done
Checking KFParticle_particleList.h ...
14/18 files checked 81% done
Checking KFParticle_sPHENIX.cc ...
15/18 files checked 85% done
Checking KFParticle_sPHENIX.h ...
16/18 files checked 91% done
Checking KFParticle_truthAndDetTools.cc ...
17/18 files checked 97% done
Checking KFParticle_truthAndDetTools.h ...
18/18 files checked 100% done

**Comment by pinkenburg** [comment]
I have rather massive changes by moving and reorganizing the includes and removing all the using namespace std; This will not merge if you start with the original code

**Comment by pinkenburg** [comment]
Give me an hour, I'll update your PR and then it's your turn, okay?

**Comment by cdean-github** [comment]
Ok, sorry about the hassle there

**Comment by pinkenburg** [comment]
I am done. Jenkins has started to work on it. I also added it to the packages which are being build, so there might be clang or gcc 4.8 complaints. I hand it back to you Dean.

**Comment by cdean-github** [comment]
Thanks! I’ll keep an eye on the build.

**Pull request merged**
