### PR TITLE
initial version drift.C

### PR DESCRIPTION
**Pull request by wjllope**
simple macro to loop over run numbers and poll the CDB to extract and plot the tpc drift velocity value for that run

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
Can you move this to our macro repo (under calibrations/tpc/TpcDVCalib). macros are notoriously hard to get through jenkins and we want to keep our macros separately

**Comment by yuxdPKU** [comment]
I can do that

**Comment by yuxdPKU** [comment]
Sorry, my origin purpose is to continue this PR, however i am not very familiar with git, so that i create a new [PR](https://github.com/sPHENIX-Collaboration/coresoftware/pull/3082)

**Comment by pinkenburg** [comment]
the macro was committed to our macro repo, closing this PR

**Pull request closed without merging**
