### PR TITLE
Micromegas qa

### PR DESCRIPTION
**Pull request by hupereir**
[comment]: <> (Please tell us something about this pull request)
- Store list of dropped waveforms (that is: not associated to a proper GTM BCO) in per-packet lists. 
- implemented JN QA histogram
- 
## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by hupereir** [comment]
Closing this PR and branch was a mistake. I thought it was merged already.

**Comment by hupereir** [comment]
... this is getting anoyign. I would really like this PR to be merge before other people continue pushing code to SingleMicromegasPoolInput (and create conflicts with this ...)

**Comment by pinkenburg** [comment]
the clang build failure is from this PR, it is not the caloreco one:
...
expression ('std::basic_ostream<char>::__ostream_type' (aka 'basic_ostream<char, std::char_traits<char>>') and 'std::list<uint64_t>' (aka 'list<unsigned long>'))
      << " gtm_bco: " << std::hex << m_gtm_bco_list << std::dec
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/gcc/12.1.0-57c96/x86_64-centos7/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/system_error:279:5: note: candidate function template not viable: no known conversion from 'std::list<uint64_t>' (aka 'list<unsigned long>') to 'const std::error_code' for 2nd argument
    operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __e)

**Comment by hupereir** [comment]
> the clang build failure is from this PR, it is not the caloreco one: ... expression ('std::basic_ostream::__ostream_type' (aka 'basic_ostream<char, std::char_traits>') and 'std::list<uint64_t>' (aka 'list')) << " gtm_bco: " << std::hex << m_gtm_bco_list << std::dec ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~ /cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/opt/sphenix/core/gcc/12.1.0-57c96/x86_64-centos7/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/system_error:279:5: note: candidate function template not viable: no known conversion from 'std::list<uint64_t>' (aka 'list') to 'const std::error_code' for 2nd argument operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __e)

I see. Will look into it. (compiles just fine with gcc)

**Comment by hupereir** [comment]
Seems that clang does not like 'template template' 
  template <template<class> class Container, class T>
    // template <class T>
  std::ostream& operator<<(std::ostream& o, const Container<T>& list)
...

**Comment by pinkenburg** [comment]
jenkins is just too slow with the checks - I don't think the remaining ones have any relevance to this PR, merging it

**Pull request merged**
