### PR TITLE
Templates from cdb

### PR DESCRIPTION
**Pull request by pinkenburg**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
waveform templates are now read from the CDB
[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by bseidlit** [comment]
Did you miss adding some changes to CaloWaveformProcessing.cc? right now this just looks for a template file in for example

/cvmfs/sphenix.sdcc.bnl.gov/gcc-12.1.0/release/release_new/new.8/share/calibrations/WaveformProcessing/templates/CEMC_TEMPLATE

**Comment by pinkenburg** [comment]
I enabled the verbosity of the cdb to be able to track down what it is actually doing, with the latest code (which will be in todays 10:24am build), I get this for the CEMC
Global Tag: ProdA_2023, domain: CEMC_TEMPLATE, timestamp: 21796... reply: /cvmfs/sphenix.sdcc.bnl.gov/calibrations/sphnxpro/cdb/CEMC_TEMPLATE/cb/ef/cbefe69a8552c6304c3d7f911fe43da6_beam_template_waveform_cemc.root
I am worried about what you see - a DB failure comes to my mind as a possible explanation. On which node did you run this?

**Comment by pinkenburg** [comment]
There are two ways to get the template. If you use set_template_file, it expects a filename where the file has to be located in $CALIBRATIONSROOT/WaveformProcessing/templates

If you want to use file from the CDB, you need to use the "name" of the calibration (which is CEMC_TEMPLATE), and you need to use set_template_name() for that:
WaveformProcessing2->set_template_name("CEMC_TEMPLATE")

**Comment by bseidlit** [comment]
Ah I see. Sorry, i just did not notice the change in member function.  It works now and all makes sense.

**Pull request merged**
