### PR TITLE
Avoid Name Clashes and Add Functionality to Select Triggers in Jet QA

### PR DESCRIPTION
**Pull request by ruse-traveler**
This PR makes two major updates to the Jet QA:

1. Certain inputs and parameters have been made user-configurable in order to avoid name clashes across modules and histograms, and to allow for the same module to be run on different jet populations in parallel;
2. And functionality has been added to all modules to allow the user to select on a specific trigger by specifying the desired trigger's index in the GL1 trigger vector.

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This PR introduces the new features described above. There have been modest changes to the API for certain modules (e.g. adding additional arguments to ctor's), and so users should update their downstream macros accordingly.

### CODE REVIEW

**Review by osbornjd — CHANGES_REQUESTED** [review]
This is somewhat nitpicky, but we have a ton of QA histograms being produced now (good). Many of them go into the same file based on whatever the production job is, so if there is not a clear naming scheme to the histogram names it might be hard to track down where they came from for someone who is looking to understand what actually went into filling the histogram. Most (probably not all, which would be nice to unify) of the QA is using a unified scheme that looks something like `h_ModuleName_HistogramName` - can we implement that here?

**Review by osbornjd — COMMENTED** [review]
One other comment - `JetQADefs` looks more like a super useful `TriggerDefs` object that would be used in many different analyses. @danjlis or @pinkenburg is there any plan for something like this, and if not lets generalize this so that we can have one centralized place for all things offline trigger decision

**Comment by ruse-traveler** [comment]
> This is somewhat nitpicky, but we have a ton of QA histograms being produced now (good). Many of them go into the same file based on whatever the production job is, so if there is not a clear naming scheme to the histogram names it might be hard to track down where they came from for someone who is looking to understand what actually went into filling the histogram. Most (probably not all, which would be nice to unify) of the QA is using a unified scheme that looks something like `h_ModuleName_HistogramName` - can we implement that here?

Sure! That will be straightforward to implement!

**Comment by osbornjd** [comment]
I guess we can leave the JetQADefs module to a future PR - it would be good to generalize this though once we get a more standardized offline trigger object

**Pull request merged**
