### PR TITLE
[Work-In-Progress] Update with EvtGen with Correct Implementation without QA Function Yet

### PR DESCRIPTION
**Pull request by MYOMAO**
[comment]: <> (Please tell us something about this pull request)

This is a fresh pull request based on the previous pull request work-in-progress attempt for the implementation of EvtGen to the sPHENIX software:

https://github.com/sPHENIX-Collaboration/coresoftware/pull/1612

We have cleaned up the codes significantly since the previous pull request attempt. In this new pull request, we have updated the EvtGen decayer files inside g4decayer as follows:

EvtGen Decayer Interface: PHEvtGenDecayer.cxx

EvtGen Decayer Register code: EvtGenExtDecayerPhysics.cc 

EvtGen Decayer Interface with GEANT code: G4EvtGenDecayer.cc

Standalone HepMC3 -> HepMC2 converter file: HepMCCompatibility.h

As well as their header files. 

Makefile.am also includes the build for EvtGen decayer modules.

Inside the PHG4Reco.cc code, I included two flags to run PYTHIA 6 decayer: bool UsePYTHIA6Decayer and EvtGen decayer: bool UseEvtGenDecayer. I also allow PHG4Reco to call PYTHIA6 decayer and EvtGen decayer. 

As for the QA codes, currently, it is removed from this commit. As I have presented in the previous software meeting: 

https://indico.bnl.gov/event/16624/contributions/66781/attachments/42651/71541/sPHENIX%20EvtGen%20HF%20Topical%20Meeting%2008-10-2022.pdf

The EvtGen and QA machinery have been validated. We will discuss in the software meeting about how to implementation of my QA codes to the coresoftware without interfering the PHG4Reco.cc.

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by MYOMAO** [comment]
Updated without conversion of HepMC3 to HepMC2 and remove root dependence

**Comment by blackcathj** [comment]
Progress! 

This time it failed in memory leaks. There is a few EvtGen related memory leaks by searching for EvtGen in 
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/1881/artifact/macros/detectors/sPHENIX/Fun4All_G4_sPHENIX.valgrind.xml/*view*/

**Comment by pinkenburg** [comment]
This PR contains 122 changes to files. Likely results of rebasing and clang-formats but just too many to go through. I just don't feel comfortable to merge this in. Please create a new PR with only your changes.

**Comment by MYOMAO** [comment]
Ok great. I will create a new pull request with only changes in my files. Thank you very much!

**Pull request closed without merging**
