### PR TITLE
Truth reco matching -- replaces pull request  Truth match #1760 

### PR DESCRIPTION
**Pull request by david-stewart**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
This pull request adds the containers in packages/trackbase to contain a mapping between tracks made with embedded tracks and track made with embedded tracks + (currently HIJING) background. This is done in the g4eval/TruthRecoTrackMatching.{h,cc} module

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
replace in g4eval/Makefile.am
-I`root-config --incdir`
by
-isystem`root-config --incdir`
this tells clang to ignore warnings from root includes. While at it 
-I$(OFFLINE_MAIN)/include/eigen3
is not needed anymore

**Comment by david-stewart** [comment]
> replace in g4eval/Makefile.am -I`root-config --incdir` by -isystem`root-config --incdir` this tells clang to ignore warnings from root includes. While at it -I$(OFFLINE_MAIN)/include/eigen3 is not needed anymore

thanks -- done and update is now pushed

**Comment by pinkenburg** [comment]
Please follow our include guidelines
https://wiki.sphenix.bnl.gov/index.php/Codingconventions#Include_Files
otherwise we are asking for problems in the future

**Comment by david-stewart** [comment]
> Please follow our include guidelines https://wiki.sphenix.bnl.gov/index.php/Codingconventions#Include_Files otherwise we are asking for problems in the future

OK -- read policy and re orded the include files. (Also, in previous git commit, alphabetized the files in the Makefile.am)

**Comment by osbornjd** [comment]
All checks pass and QA looks fine - with your approval @david-stewart I will merge.

**Comment by david-stewart** [comment]
> All checks pass and QA looks fine - with your approval @david-stewart that this is ready to go, I will merge.

thanks! I approve

**Pull request merged**
