### PR TITLE
Revised loop structure and fixed some bugs/typos, omitted auto-generated codes using survey data

### PR DESCRIPTION
**Pull request by josephbertaux**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Review by osbornjd — COMMENTED** [review]
Shouldn't we put the survey information into the CDB rather than in a function which returns the transform? This seems like it is calibration type information and thus it should go in the CDB rather than hard coded into our main repo

**Comment by pinkenburg** [comment]
I second that, CDBTTrees are made for this and we should also keep the code which generates those numbers and their source (that can be in a different repo, but should be referenced in the file so we know where the numbers come from)

**Comment by josephbertaux** [comment]
I'll make the source code put these into a CDBTree, I did something similar with the mapping of felix channels b/c I originally did something similar as well (auto-generated switch-case statement).

**Comment by josephbertaux** [comment]
Omitted the auto-generated codes from this PR, now it just has the bug fixes/revisions.

**Pull request merged**
