### PR TITLE
new evaluation module

### PR DESCRIPTION
**Pull request by hupereir**
[comment]: <> (Please tell us something about this pull request)
As discussed (in particular with @bogui56) during last few tracking meetings, this PR introduces a new evaluation module, called TrackEvaluation, that fills variable size structures containing track and cluster informations hopefully suitable for studying the possibility to compress our output format. (this is also in essence the module I used to get all types of residual plots that have been circulating around for the last 6 month). Tracks and clusters are stored in a node called "TrackEvaluationContainer". The structure using only std::vectors, the node content can be drawn directly from  a root macro without the need for loading any coresoftware-specific libraries (as with a flat ntuple)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people) (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

- the name of the module/node can be changed if this one is deemed too generic. 
- need to either include in our official macros or provide offline a sample macro to include the module (to be discussed) 
- need some exemples on how the output can be used. Possibly some slides at the next tracking meeting ?
- comments/suggestions for improvement welcome

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by hupereir** [comment]
Commit 35f3990 should fix the clang error.
For the scan error, I am confused because none of the errors reported seem related to this change. Can @pinkenburg or @blackcathj double check ? 
Thx !

**Comment by blackcathj** [comment]
> Commit [35f3990](https://github.com/sPHENIX-Collaboration/coresoftware/commit/35f39904f81fffb67da02800ee90dbf7276f1002) should fix the clang error.
> For the scan error, I am confused because none of the errors reported seem related to this change. Can @pinkenburg or @blackcathj double check ?
> Thx !

Many of the scan-build errors come from the on-going effort to separate out EIC-related classes ( https://github.com/sPHENIX-Collaboration/coresoftware/pull/1138 ). Don't worry about it. And for the next few days, the scan error will not propagate to the final pull request check result.

**Comment by hupereir** [comment]
From what I can tell, none of the failures reported above are related to this change. Should be good to go.

**Comment by blackcathj** [comment]
Strange error on the calorimeter QA. Restarting again. 
Scan build error is irrelevant to this pull request. Please ignore.

**Pull request merged**
