### PR TITLE
Distortion correction fixes

### PR DESCRIPTION
**Pull request by hupereir**
- remove use of now obsolete get_acts_covariance()
- cleanup

This fixes getting Nan for all reconstructed distortion corrections
Also adapts the Genfit version of the distortion corrections to new track interface, and make acts/genfit distortion reconstruction more consistent. 

We still need the genfit path in order to be able to compare with acts in detail.

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
Push an empty commit to retrigger Jenkins, it hung yesterday for some other issues that have since been fixed.

**Comment by osbornjd** [comment]
QA looks fine and failure is due to ongoing tpc overlap issue, if you approve Hugo we can merge

**Comment by hupereir** [comment]
> QA looks fine and failure is due to ongoing tpc overlap issue, if you approve Hugo we can merge (unless there are ongoing jobs from most recent commits)

@osbornjd 
yeah. Let me run a few more (distortion specific) tests before pushing this. I might need to append more commits to this PR before it is good to go.

Hugo

**Comment by sPHENIX-GitHub-l** [comment]
Agreed that we should investigate. This is with static distortions or average - static ? Here with own macro and average-static, I get no such errors.

However with static distortions being significantly (x10) larger, I would not be surprised that this happens yes


Hugo

________________________________
From: sPHENIX-GitHub-l ***@***.***> on behalf of Joe Osborn ***@***.***>
Sent: Friday, September 16, 2022 8:18 AM
To: sPHENIX-Collaboration/coresoftware
Cc: Subscribed
Subject: [EXTERNAL] Re: [Sphenix-github-l] [sPHENIX-Collaboration/coresoftware] Distortion correction fixes (PR #1652)


Sounds good we will merge this. however this just reminded me that Chris reported an issue in the MDC macros with the distortions. Right now there are a bunch of TH3 histogram out of bounds interpolation errors being thrown - my guess is that somehow the distortion maps aren't being loaded correctly and/or aren't being accessed correctly. Have you seen this in any of your tests? It's unrelated to this PR as it is merged already - in any case we should investigate with Chris

**Pull request merged**
