### PR TITLE
Acts source link into trackbase

### PR DESCRIPTION
**Pull request by osbornjd**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
This PR refactors the Acts source link class into our `trackbase` package so that we can use it with other sPHENIX type objects, e.g. those defined in `TrkrDefs`.

It also fixes up the GSF to use this and a custom implemented GSF track fitter, analogously to the KalmanFitter.

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
The ioselect.h compilation problems should be solved, what's left is cppcheck

**Comment by osbornjd** [comment]
clang build now fails with some warnings in boost - is this something else new?

**Comment by pinkenburg** [comment]
that needs a -Wno-deprecated-declarations in the clang++ flags in the configure.ac

**Comment by osbornjd** [comment]
> that needs a -Wno-deprecated-declarations in the clang++ flags in the configure.ac

This didn't work for me (I was able to reproduce the clang error) but adding the following
```
#pragma GCC diagnostic ignored "-Werror"
#pragma GCC diagnostic ignored "-Wunused-value"
```
around the Acts include that calls this boost header does the trick - is this sufficient? I'll push a commit so you can see explicitly what I'm talking about

**Comment by osbornjd** [comment]
I spoke too soon - this works for clang but not for gcc...

**Pull request merged**
