### PR TITLE
mvtx dead pixel maps simulations

### PR DESCRIPTION
**Pull request by pedroanietom**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
Please accept the github invite I just sent to you.

**Comment by osbornjd** [comment]
@pinkenburg can we put this file into the CDB as a test MVTX dead map?
/sphenix/user/pnietomar/mvtx/dead_pixel_mask.root
Then we can modify this PR to actually be able to run

**Comment by pinkenburg** [comment]
I just added it under MVTX_DeadPixelMap, give it about 30 minutes for the cvmfs release (unlike the farm, jenkins cannot read from the nfs mounted area)

**Comment by osbornjd** [comment]
Thanks, I'll try to update this PR tomorrow with the CDB call

**Comment by osbornjd** [comment]
@pedroanietom somehow the commit history has gotten mixed up on this PR as there are commits included in it that you didn't author. Could you close this PR and reopen a different one with only your commits that add the dead pixel simulation? If you need help doing this, just let me know and we can chat about it

**Comment by pedroanietom** [comment]
@osbornjd I've noticed the mixed commit history in the pull request as well. I will close the current PR and open a new one with only the commits related to the dead pixel simulation.

**Pull request closed without merging**
