### PR TITLE
Pull

### PR DESCRIPTION
**Pull request by zchwaknn**
image

### CODE REVIEW

**Comment by blackcathj** [comment]
Thanks for the immediate follow up! 

For the eta and phi pull distribution plots, could you also zoom into the x-axis range of [-5, 5]? The goal is to check the width of the Gauss core to be near 1.

**Comment by zchwaknn** [comment]
image

**Comment by blackcathj** [comment]
@zchwaknn  Is this the identical plot as in the 1st comment?

**Comment by zchwaknn** [comment]
I was working in the same windows that were just generated, clicked on the X axes, right-clicked, and selected SetLimits. I entered -5 and 5.

**Comment by blackcathj** [comment]
Please try something like this in the drawing stage:
```c++
ntp_track->Draw("(pt-gpt)/detapt >> hEtaPull(100,-5,5)")
```

**Comment by zchwaknn** [comment]
image
image

**Pull request merged**
