### PR TITLE
cluster error parametrization update

### PR DESCRIPTION
**Pull request by bogui56**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
We cannot just add or remove data members in those version classes. This does affect the readback. Is TrackEvaluationContainerv1.h being saved in past DSTs? If so please update the version to v2

**Comment by pinkenburg** [comment]
Then we are good. I really want to avoid a repeat of the disaster we had in mdc1 where a change in the tracking object completely messed up the analysis of the data

**Comment by osbornjd** [comment]
The distributions are obviously nontrivially changed but the momentum resolution degrades slightly. I assume this is because the pulls on some of the cluster distributions have shrunk, e.g. the TPC cluster z pulls are significantly narrower than before.

**Comment by osbornjd** [comment]
Also in reference to Chris' comment, I think the changes in the `TrkrClusterv4` will cause DST readback issues since we are using this cluster version right now. While the evaluation container is probably not a big deal since this is primarily only used by tracking experts, the cluster object change might wreak havoc

**Comment by sPHENIX-GitHub-l** [comment]
I agree with Joe about the TrkrCluster changes. If what is stored changes, it has to be versioned.

Tony
________________________________

**Comment by bogui56** [comment]
Hi, 

regardons the storage nothing has changed, we still have a unsigned short int data member for the 
charge information. Before we put the total cluster charge in the data member, now I put the max adc in the high 8 bits and the total charge in the lower 8 bits. 
Reading back old clusters would work, but obviously the max adc would return zero.

If that warrants a new cluster version, that can be arranged. 

Does someone remember where the reference comes from? Is this still from cluster version 3 times? When did we last update this?

Cheers

  Christof

**Comment by pinkenburg** [comment]
the commit adds a static unsigned int. We would have to see what the root streamer makes out of this - I would not be surprised if it stores it and then tells you the objects don't match. It is used in one place - if it is not used outside of this source I would either just hardcode this as 8 or use a #define (where one has to be careful that this is set in every source which includes this file

**Comment by bogui56** [comment]
Ok, there was not supposed to be a new data member, let me check.

**Comment by osbornjd** [comment]
@bogui56 just double checking but I think we decided to merge this and then switch to v5 at the macro level, correct? The parameterization at least looks like it has returned to the previous performance.

**Comment by hupereir** [comment]
Hi, 
Maybe I missed something. Why does this PR come with a new version of the TrkrClusterContainer (namely TrkrClusterContainerV5) ? As far as I could tell, it is _identical_ to TrkrClusterContainerv4 except for the class name. What is the actual difference that justifies scheme evolution ? 
If there is none, I would recommand removing the class and stick to v4. 
(note that this is orthogonal to having a new version for TrkrCluster)

**Comment by hupereir** [comment]
In fact, checking further, the class TrkrClusterContainerV5 is not used. All existing clusterizers are still creating instances of TrkrClusterContainerv4
So unless there is an objection, I would like to prepare a separate PR that removes this unused class. It just adds confusion ...

**Comment by bogui56** [comment]
You are right, we can remove this again.

**Comment by bogui56** [comment]
Yes, thats the plan. The macro pull request to move to v5 as default is out. 
The paramterization was off before because the TpcClusterizer update to write the cluster max adc
was missing from the pull request by accident. A big part of the new parameterization is the 
max arc dépendance, so now it looks mach better. 

Cheers

   Christof

**Pull request merged**
