### PR TITLE
Slimmed down version of TrackInfo to push

### PR DESCRIPTION
**Pull request by aopatton**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
clang-tidy complains about [this](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/clang-tidy-pipeline/25/clang-tidy/folder.-1635432539/fileName.-1036866451/source.3e6f2615-873e-4096-98db-cb69b3fe7f92/#81) parameter not having a name, but then also complains if you give it a name since it is not used in the function...

**Comment by pinkenburg** [comment]
> clang-tidy complains about [this](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/clang-tidy-pipeline/25/clang-tidy/folder.-1635432539/fileName.-1036866451/source.3e6f2615-873e-4096-98db-cb69b3fe7f92/#81) parameter not having a name, but then also complains if you give it a name since it is not used in the function...

it wants something like (PHCompositeNode * /* topNode*/)
but this method is empty - why don't you just remove it and leave it up to the base class to return EVENT_OK?

**Comment by osbornjd** [comment]
Fair enough, I fixed this and applied clang-format. Hopefully this should pass the CI now other than the missing includes that it can't find since it is not run on the local build

**Comment by osbornjd** [comment]
The only clang-tidy errors that remain are the missing includes it can't find since it is not run on the local build produced as a part of the jenkins check, see [here](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/clang-tidy-pipeline/29/clang-tidy/). Merging

**Pull request merged**
