### PR TITLE
Tpc deltaz correction

### PR DESCRIPTION
**Pull request by hupereir**
[comment]: <> (Please tell us something about this pull request)
This PR introduces a per-track delta_z correction to the TPC clusters, to account for particle's finite velocity and propagation in the TPC. 
Consequently simplified Delta_z correction in TpcClusterizer to a single constant value that accounts for the TPC shaping time.
See details at: https://indico.bnl.gov/event/13716/contributions/57178/attachments/38262/63057/talk.pdf
Also included small cleanup/optimizations to visited tracking modules 

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [x] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)
https://github.com/sPHENIX-Collaboration/macros/pull/465

### CODE REVIEW

**Comment by pinkenburg** [comment]
The vertexing QA looks significantly worse (plots at the bottom), can someone verify if this is expected, or is this the changed reference with improvements after the PR was submitted
?

**Comment by blackcathj** [comment]
> The vertexing QA looks significantly worse (plots at the bottom), can someone verify if this is expected, or is this the changed reference with improvements after the PR was submitted ?

I agree, the DCAz get larger at high pT suggesting influence of TPC z shift dragging into the DCA determination: 
image

Let me try to run this PR with sPHENIX-Collaboration/macros#465

**Comment by blackcathj** [comment]
> The vertexing QA looks significantly worse (plots at the bottom), can someone verify if this is expected, or is this the changed reference with improvements after the PR was submitted ?

@hupereir @pinkenburg this PR works well with sPHENIX-Collaboration/macros#465 in QA : https://github.com/sPHENIX-Collaboration/macros/pull/465/checks?check_run_id=4160685485

Suggest we merge it and update reference @jdosbo 

image

**Comment by pinkenburg** [comment]
Let me merge this and the macro so we get this in todays new build

**Pull request merged**
