### PR TITLE
Tpot new geometry

### PR DESCRIPTION
**Pull request by hupereir**
[comment]: <> (Please tell us something about this pull request)
This implements the latest TPOT geometry directly into geant 4. 
See https://indico.bnl.gov/event/14546/contributions/59761/attachments/39625/65748/talk.pdf for details
Depends on https://github.com/sPHENIX-Collaboration/macros/pull/488 and https://github.com/sPHENIX-Collaboration/coresoftware/pull/1400

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [x] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)
https://github.com/sPHENIX-Collaboration/macros/pull/488

### CODE REVIEW

**Comment by osbornjd** [comment]
@hupereir there are a lot of nontrivial changes to the low multiplicity tracking QA from this PR, e.g. the momentum resolution degrades by almost a factor of 2. Is it understood what this is from?

**Comment by hupereir** [comment]
@osbornjd 
The changes in the Micromegas QA (small modifications of the residuals distributions) are understood: new position of the TPOT, new pitch. And are not dramatic

The dramatic changes in the tracking QA and the Vertex QA, I suspect they come from inconsistent material map (again), because volumes definitions and hierarchy have changed with the new geometry (no more fake surfaces, no more cylinder micromomegas), but I cannot test/verify that this is indeed the case

Hugo

**Comment by osbornjd** [comment]
I could see that being the case for the momentum resolution but the DCA distribution changes are surprising. I will try to take a look at the new volume assignments later today and see if there is an easy way to check if this might be the cause.

**Comment by hupereir** [comment]
The reduction of the number of micromegas clusters on the "reco cluster per layer per track" plots is due to the fact that there is now only 8 TPOT modules instead of 26 before. To me it says that the track finding works essentially the same as before (which I have verified independently). Now, more than 60% of the TPC acceptance has no TPOT at all: it should have no impact on the momentum resolution, whatsoever

**Comment by osbornjd** [comment]
Sure, I expected that the TPOT QA would change but was surprised to see such drastic changes in the tracking/vertexing. But let me take a look this afternoon and I'll report back.

**Comment by osbornjd** [comment]
It does look like the new volume elements have different mappings, so the material map is broken. I will try to update it tomorrow with the new geometry. This should definitely fix the momentum resolution and hopefully the DCA as well as shown in the QA for this PR.

BTW @blackcathj let's not update the reference so that we have a clear indication of what the performance was pending an upcoming PR to update the material map.

**Pull request merged**
