### PR TITLE
Update the TrkrCluster's for the truth track to use local geometry.

### PR DESCRIPTION
**Pull request by david-stewart**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
The Embedded ("Truth") tracks are associated with TrkrClusters that were set using global phi and time geometries. This PR modifies them to use the local geometries (in the TPC Pad Plane for each hit), such that they can be compared with the reconstructed track TrkrClusters.

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by david-stewart** [comment]
Hi @pinkenburg, in the build file where things fail [[here](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-ScanBuild-gcc12/14//artifact/build/scan/rebuild.log)], this appears to be the terminal error. I think it is independent of my code, but would be happy to check anything I can/ought. 
```
In file included from input_line_9:85:
/var/lib/jenkins/workspace/sPHENIX/Build-ScanBuild-gcc12/online_distribution/newbasic/event_io.h:5:10: fatal error: 'ioselect.h' file not found
#include "ioselect.h"
         ^~~~~~~~~~~~
In file included from input_line_9:87:
In file included from /var/lib/jenkins/workspace/sPHENIX/Build-ScanBuild-gcc12/online_distribution/newbasic/packet.h:7:
/var/lib/jenkins/workspace/sPHENIX/Build-ScanBuild-gcc12/online_distribution/newbasic/event_io.h:5:10: fatal error: 'ioselect.h' file not found
#include "ioselect.h"
         ^~~~~~~~~~~~
Error: rootcint: compilation failure (./msg_Dictffb42ee2c9_dictUmbrella.h)
make: *** [msg_Dict.C] Error 1
make: *** Waiting for unfinished jobs....
Error: rootcint: compilation failure (./event_Dict2290a9a002_dictUmbrella.h)
make: *** [event_Dict.C] Error 1
system make -l 32 -j 32 install-data>> /var/lib/jenkins/workspace/sPHENIX/Build-ScanBuild-gcc12/build/scan/rebuild.log 2>&1 failed: 512
```

**Comment by pinkenburg** [comment]
I think this was a Makefile problem which I don't see in our daily scan builds. The issue is that ioselect.h wasn't explicitly in the dependency of the dictionary and therefore created later during the header installation. I added it to the dictionary dependency which should take care of this, here is the PR
https://github.com/sPHENIX-Collaboration/online_distribution/pull/87
This is not in the coresoftware - you don't need to do anything to straighten this out

**Comment by osbornjd** [comment]
@david-stewart can you push an empty commit or update with master to re-trigger jenkins and have this checked? I think you said it was ready to go but it failed some things when we were updating to gcc12 - should be smoother now

**Comment by david-stewart** [comment]
> @david-stewart can you push an empty commit or update with master to re-trigger jenkins and have this checked? I think you said it was ready to go but it failed some things when we were updating to gcc12 - should be smoother now

Just pushed a new request. Jenkins failed in at least one instance for a few unused private class members that I commented out.
It sounds like there will be a new algorithm for the subsurface from hitsetkey + phi-bin lookup in the TpcClusterizer (or at least ActsGeometry and used there). I'll update this code accordingly when that happens, but I don't think there is any reason to not merge this branch for now, assuming that it all checks out with Jenkins etc...

**Comment by osbornjd** [comment]
Ah, so does [1776](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1776) replace this PR?

**Comment by david-stewart** [comment]
Yes! Good catch. I will remove this PR request in favor of [1776](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1776)

**Pull request closed without merging**
