### PR TITLE
update GlobalQA-- re-add mbd null vertex count plot, update zdc plots

### PR DESCRIPTION
**Pull request by eumaka**
- plots from  [PR#2971](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2971) added here after discussion with Blair and Sam. Do not merge PR 2971 (potential merge conflict)
- update with new zdc object

### CODE REVIEW

**Comment by bseidlit** [comment]
OK, I am merging this but didn't we agree you would add Sam's stuff? np if you didn't have time.

**Comment by pinkenburg** [comment]
That merge was premature - this package is not in our build, any compilation error will kill subsequent PRs (and our daily builds). For a PR proposing a new package we have to make sure it is in the packages.txt in our utilities repo, otherwise it is not being build and only cppcheck and clang-tidy are run over it.

**Comment by bseidlit** [comment]
What do you mean? This package was in several days ago?

**Comment by bseidlit** [comment]
Ahh I see. I have merged this package I think from it's conception.

**Comment by bseidlit** [comment]
OK, Ejiro steered me to this.  I didn't even know this existed... sorry.  Can we fix this now?

**Comment by pinkenburg** [comment]
I just added it and make an unrelated PR, this will test this one and then we'll see (it should be fine)

**Comment by bseidlit** [comment]
OK, I see, this makes some sense as to what is actually getting built.   I guess we just wait.

**Comment by eumaka** [comment]
Cool, np. Also FYI, same stuff is in there.

**Pull request merged**
