### PR TITLE
Jet container switch

### PR DESCRIPTION
**Pull request by david-stewart**
[comment]: <> (Please tell us something about this pull request)
This commit switches the default container on the node tree from `JetMap` to `JetContainer`, which contains the data in `TClonesArray` instead of `std::map`. It also switches the default object to contain jets from `Jetv1` to `Jetv2`, the second of which moves the constituents from a `std::multimap` to a `std::vector<std::pair<Jet::SRC,unsigned int>>`. This second change is the more intrusive in terms of the code's interfaces as the access to the constituent members has changed. The old access was via iterators to the multimap, but the new one either to the vector or iterators to parts of the vector. Therefore the call methods have changed.

This PR updates all the call methods in the coresoftware. There are no changes that are required in the macros library. There may, however, be some call methods in the [analysis Github](https://github.com/sPHENIX-Collaboration/analysis) code that will need to be updated, but I haven't checked yet. So, perhaps we will have to have some communication before making the official switch.

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by david-stewart** [comment]
Hi @blackcathj, (cc'd here perhaps also @pinkenburg, @osbornjd, @hupereir)  this PR is intended to just switch the default containers (`JetMap`->`JetContainer`, `Jetv1`->`Jetv2`), and should have identical output. Should I care that QA checks don't all come back with a p-value = 1? (most do, including for two e- particle embeddings, but for whatever reason the two pi+ checks don't).  
Thanks!

**Comment by pinkenburg** [comment]
jenkins is fine - the calorimeter q/a needs updated references, they have been off for a long time.

The global replacement FIXME --> fixme introduces a lot of noise and changes in sources which have nothing to do with this (GenFit, Intt hit reco, tpc). I don't mind if changes are done in sources one works on but changes across the board are counter productive.

What is the purpose of the new Makefile_subjectind.am?

**Comment by osbornjd** [comment]
There are also invalid reads in the jet container from the QA module, that I would suspect are from this PR, e.g. here 
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/3910/valgrindResult/pid=202282,0x175249/

**Comment by david-stewart** [comment]
Thanks; I'll look into it

**Comment by david-stewart** [comment]
I have the go-ahead from the software meeting and the Jet Structure group. Additionally, I have some documentation posted at [on](https://wiki.sphenix.bnl.gov/index.php/Jet_Structure_Topical_Group)[ the wiki here](https://wiki.sphenix.bnl.gov/index.php/Jet_Structure_Topical_Group), as well as posting an announcement with a link to that documentation on Mattermost.
So, I think all the boxes are checked and [PR 2371](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2371) is good to be merged.

(I'll send this via email, too; thanks!)

**Pull request merged**
