### PR TITLE
Track reco changes for real data

### PR DESCRIPTION
**Pull request by cdean-github**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

Cluster z size wasnt filled correctly for the MVTX when we see streaks. z size is a signed char so has max size of 127. Any cluster with z size > 127 is now dropped from the clustering. [Discussion in tracking meeting](https://indico.bnl.gov/event/23149/)

KFParticle wasnt reading the magnetic field map correctly so wouldnt process any tracks (field was set to 7x10^22 tesla!). Had to fix this for K-short reconstruction

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by ycorrales** [comment]
why are we using char and not uint8_t for size values, or do we use a negative cluster size in z or rphi for some purpose?

**Comment by cdean-github** [comment]
> why are we using char and not uint8_t for size values, or do we use a negative cluster size in z or rphi for some purpose?

There's no need for a negative cluster size in the INTT or MVTX (that Im aware of). The char was used to save space on the DST before we knew about the beam backgrounds

**Comment by osbornjd** [comment]
I don't think it was ever anticipated needing to have more than 127 size clusters in phi/z. We could revisit this

**Comment by ycorrales** [comment]
> > Why are we using char and not uint8_t for size values, or do we use a negative cluster size in z or rphi for some purpose?
> 
> There's no need for a negative cluster size in the INTT or MVTX (that I'm aware of). The char was used to save space on the DST before we knew about the beam backgrounds



> > Why are we using char and not uint8_t for size values, or do we use a negative cluster size in z or rphi for some purpose?
> 
> There's no need for a negative cluster size in the INTT or MVTX (that I'm aware of). The char was used to save space on the DST before we knew about the beam backgrounds

yes, but char and uint8_t have the same size and we can use more positive values. I expect an error from the warning due to cast different signed integer variables.

**Comment by blackcathj** [comment]
There was a brief moment memory resource on the CI worker nodes reached 100% that lead to check fails. Please ignore the failed tracking QA job. 

The full memory lead to failed to start one of the thread in TPC clustering module, which lead to one of the tracking QA job crashed. Here is the log file: 
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-tracking-low-occupancy-qa/5296/artifact/macros/detectors/sPHENIX/G4sPHENIX_job_1.log

**Pull request merged**
