### PR TITLE
Update DCA covariance and magnetic field

### PR DESCRIPTION
**Pull request by osbornjd**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [X] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people) (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This PR adds the feature to run the tracking with a constant magnetic field. This produces the best performance plots right now, as Acts assumes a constant field and may have a bug when it is interpreting the field map. 

This PR also fixes a bug in the DCA uncertainty calculation. It now uses the rotated covariance matrix back from the Acts basis to the sPHENIX basis. 

## TODOs (if applicable)

Figure out why Acts has a difficult time interpreting our field map. That is for another PR.

## Links to other PRs in macros and calibration repositories (if applicable)

[Here](https://github.com/sPHENIX-Collaboration/macros/pull/361) is the macros PR which allows running the default Acts chain with either the PHTpcTracker or CASeeder, with either the constant or field map magnetic field.

### CODE REVIEW

**Comment by osbornjd** [comment]
BTW the performance plots that will be shown at the 10th sPHENIX collaboration meeting will correspond to the repository in the state given by this PR

**Comment by osbornjd** [comment]
The uncertainties should be correct now after the latest commits - I checked and the (x,y,z) all have approximately the same uncertainties, and the px,py,pz have uncertainties that correspond approximately to the momentum resolution

**Comment by blackcathj** [comment]
There is a temp. problem on the main Jenkins server. The last check failed and let me check into it.

**Comment by blackcathj** [comment]
OK. Some change in the code introduced a `stdout` print as following that filled up the disks when QA simulation was launched ....

```


Global sPHENIX cov : 

0.408596, 0.0346545, -0.403718, 2.56428, 1.52273, 2.78078, 
0.0346545, 0.365808, -0.233651, -4.47635, -2.65696, -4.74909, 
-0.403718, -0.233651, 0.508482, 0.0457749, 0.026519, -0.00816996, 
2.56428, -4.47635, 0.0457749, 196.412, 115.842, 209.174, 
1.52273, -2.65696, 0.026519, 115.842, 68.324, 123.369, 
2.78078, -4.74909, -0.00816996, 209.174, 123.369, 222.771, 

Global sphenix cov after unit conv: 

0.00408596, 0.000346545, -0.00403718, 0.256428, 0.152273, 0.278078, 
0.000346545, 0.00365808, -0.00233651, -0.447635, -0.265696, -0.474909, 
-0.00403718, -0.00233651, 0.00508482, 0.00457749, 0.0026519, -0.000816996, 
0.256428, -0.447635, 0.00457749, 196.412, 115.842, 209.174, 
0.152273, -0.265696, 0.0026519, 115.842, 68.324, 123.369, 
0.278078, -0.474909, -0.000816996, 209.174, 123.369, 222.771, 

Initial Acts covariance: 

0.0346517, 0.000245753, 0.000169061, 8.02193e-07, -0.000337818, -0.000919993, 
0.000245753, 0.210222, 2.33445e-06, -0.000380771, -5.30305e-06, -0.141888, 
0.000169061, 2.33445e-06, 1.35012e-06, 3.73646e-09, -4.85983e-06, -6.40508e-06, 
8.02193e-07, -0.000380771, 3.73646e-09, 1.07328e-06, -6.71238e-09, 0.0002565, 
-0.000337818, -5.30305e-06, -4.85983e-06, -6.71238e-09, 4.03058e-05, 1.98045e-05, 
-0.000919993, -0.141888, -6.40508e-06, 0.0002565, 1.98045e-05, 1.09579, 

....
```

**Comment by osbornjd** [comment]
I made a mistake and forgot to turn the verbosity of the covariance matrix calculator to off (Tony notified me of this also). I pushed the change in [this](https://github.com/sPHENIX-Collaboration/coresoftware/pull/1059/commits/26c28b2d08604f6986caf7a66edb23851c7a7fa6) commit. Sorry for overwhelming Jenkins... but it should be fixed now and would just require restarting the build, I think.

**Comment by osbornjd** [comment]
@blackcathj I see a valgrind error but the page comes up blank with some sort java stack trace - was there an issue with Jenkins?

**Comment by blackcathj** [comment]
> @blackcathj I see a valgrind error but the page comes up blank with a java stack trace - was there an issue with Jenkins?

Jenkins server was rebooted during the weekend which unfortunately wipe out the webpage format of previous reports. Nonetheless, we can always access [the archived XML valgrind report](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/169/artifact/macros/detectors/sPHENIX/Fun4All_G4_sPHENIX.valgrind.xml/*view*/) as on the [job summary page](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-detector-valgrind-pipeline/169/). As we have a large number of valgrind error at the moment, the XML report would be easier to search through

**Pull request merged**
