### PR TITLE
Event Plane Detector geometry functions 

### PR DESCRIPTION
**Pull request by bschaefe**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
I don't see a place where a copy ctor or the = operator would be used. I would just delete them to make cppcheck happy. If it is used somewhere the compiler will not let that through and we can deal with that when needed

**Comment by bschaefe** [comment]
Hi.  I'm now confused, as the original warnings were: [noCopyConstructor] and [noOperatorEq].  I added these two functions in an attempt to remove the warning and have the pull request go through.  Certainly I can remove them though.

**Comment by bschaefe** [comment]
This is very helpful, and much appreciated.  It will be a little bit.

**Comment by pinkenburg** [comment]
I had a look at the overlap in the previous version. It was caused by unphysical vacuum volumes (BackwardBeamLineEnclosure and ForwardBeamLineEnclosure) which ensure that vacuum extends up to the zdcs without implementing a beam pipe. Please move the epd to where it is supposed to be and then  we can adjust those volumes accordingly

**Comment by pinkenburg** [comment]
The overlap is a problem by our non physical vacuum volume. I'll merge this and fix it once we have a fresh build

**Pull request merged**
