### PR TITLE
Add oHCAL tile map response

### PR DESCRIPTION
**Pull request by johnlajoie**
[comment]: <> (Please tell us something about this pull request)

This PR uses the oHCAL tile map response measured by MEPHI to modify the oHCAL light yield generated from energy deposits in the scintillator to reflect the measured non-uniformity in the scintillating tiles. 

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [X] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This PR adds a more realistic light yield response from the oHCAL scintillating tiles based on the measured tile response. As such, the light yield will more accurately reflect the features of the fiber embedded in the tile, proximity to the light blocker, etc. Because the scintillator in G4 is implemented as a single subdivided volume (no boundaries) this will also have the effect of introducing boundaries between the tiles. 

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

At this point this is a draft pull request for testing with Jenkins. I'm not sure if the tile response will change things enough that Jenkins will puke, but it will be good to see. 

Something else that could also be considered would be interpolating between the map bins (0.5cm).  We thought about this, but decided against it.  There are fluctuations in the response along the boundaries that would propagate if we did that and they would potentially need to be smoothed.  The 0.5cm size is much larger than the typical hadronic shower scale that we felt is was better not to overly-process and massage the map. 

Currently running a large sample with the same random seed to compare directly the tile response in local coordinates with and without the map response added.  Will add that to the PR when completed. 

## Links to other PRs in macros and calibration repositories (if applicable)

The outer HCAL tile map itself was introduced by the pull request: 

https://github.com/sPHENIX-Collaboration/calibrations/pull/85

which has already been merged,

### CODE REVIEW

**Comment by blackcathj** [comment]
The results are actually pretty consistent, though bins does migrate around after the photon generation step as expected.

The PR QA would not have enough statistics to tell fine difference, e.g. hadronic energy resolution, though. 

image

image

**Comment by johnlajoie** [comment]
This really looks about as I expected. the maxium deviation (from minimum to maximum) within a tile can be quite large (more than a factor of two), but this is looking at the extreme points in the tile maps. As a shower samples the tiles a lot averages out and you are just left with the secondary effect of did you sample a little more in one area than another.  The end result is the actual effect on things like energy distributions should look small. 

What will be very interesting to look at will be the constant term in the energy resolution. I've long suspected that the tile non-uniformity will show up there at some level. 

Let me just pull together the ratio plot from our tests and add that to the PR as a double-check. Once that is done I think we should be good to merge. 

Ejiro has started work on the iHCAL tile maps;  the procedure will mirror this one.

**Comment by johnlajoie** [comment]
Here's the result of running 1000 single pion events (5 per event) in two ways - the top panel is without the new tile response map, the bottom is with the new tile response map.  These events were run with the same initial random seed so they are basically the same events modulo the tile response - this makes it easier to see the effect in a smaller event sample. 

compare

Hard to see the difference by eye.  If I take the ratio:

ratio

Now you can clearly see the effect of the tile response map.

**Comment by johnlajoie** [comment]
I had a quick look at the valgrind report but the complaints seem to be in other parts of the simulation code. I think this is ready to merge.

**Pull request merged**
