### PR TITLE
reconstruct SMD, update sEPD masking

### PR DESCRIPTION
**Pull request by eumaka**
Changes:

For ZDC-SMD: reconstruct all 52 channels
For sEPD: Mask channels not instrumented using updated 2024 map

### CODE REVIEW

**Comment by pinkenburg** [comment]
The reading for 2023 zdc data in the Fun4All_Year1.C macro fails

**Comment by eumaka** [comment]
If you are running it over 2023 data it will fail at calibration state: 
/home/phnxbld/sPHENIX/gcc-12.1.0/ana/source/coresoftware/offline/database/cdbobjects/CDBTTree.cc:691:  Could not find channel 16 for zdc_calib in float calibrations

Remember what's in the CDB, is a file with 16 channels

**Comment by eumaka** [comment]
I just made another calibration file with 52 channels (will be 0 for the extra channels (SMD+Veto)), and ran a private DST. It works fine for the 2023 data. Once the new calibration file is in the CDB, it should be good to go.

**Comment by pinkenburg** [comment]
The problem is that we need to run a towerbuilder over the 2023 data. The current Fun4All_Year1.C macro crashes - that is a problem which has to be fixed. It might mean that this macro needs a change but whatever we do - we have to preserve the ability to process run 2023 data

**Pull request merged**
