### PR TITLE
refactor: Remove cluster version flags

### PR DESCRIPTION
**Pull request by osbornjd**
## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This PR removes the cluster version flag from the macros and coresoftware, which opens us up to possible mistakes or places in the code where the correct version is not used in some weird way (e.g. as I found in ALICEKF.cc). In any case it creates a lot of extra code bloat that is not needed. Now that the base class is properly implemented there is no need for dynamic_casting anything and if a particular component does not exist in the implemented version it will be called from the base class.

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)
Requires https://github.com/sPHENIX-Collaboration/macros/pull/661

### CODE REVIEW

**Comment by osbornjd** [comment]
@bogui56 Please let me know if you have objections to this, it removes a lot of unnecessary and duplicated code. We should try to create a single interface by which the parameterized clusters access their uncertainties (e.g. some object that gets put on the node tree, which would also allow us to create only one instance of the ClusErrPara class)

**Comment by osbornjd** [comment]
Here's a build
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc12/1351/

**Comment by osbornjd** [comment]
Here's a build with cppcheck fixed
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc12/1354/

**Comment by osbornjd** [comment]
Build passes with no substantial changes to the QA
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc12/1354/
will mark as draft until I hear from Christof

**Comment by bogui56** [comment]
I agree this needs cleanup.

I have no objection to simplifying this as long as we keep the functionality to run with
varying cluster objects with different information content.

cheers

   Christof


On 3. Aug 2023, at 20:19, Joe Osborn ***@***.***> wrote:



@bogui56<https://github.com/bogui56> Please let me know if you have objections to this, it removes a lot of unnecessary and duplicated code. We should try to create a single interface by which the parameterized clusters access their uncertainties (e.g. some object that gets put on the node tree, which would also allow us to create only one instance of the ClusErrPara class)

**Comment by osbornjd** [comment]
Yes we can always go back to v4 by just switching what type of implemented class is explicitly created (v4 or v5 or v-whatever). What we should do is just have the parameterized error class accessed by the actual cluster object in some way (or maybe the clusterizers? TBD) to create the errors when the cluster is created and then just store them in the usual spot. Then the access for the uncertainty of the cluster will always be the same with the usual `getRPhiError` or whatever.

**Comment by osbornjd** [comment]
Christof and Jenkins approve, merging

**Pull request merged**
