### PR TITLE
Development of new QA module

### PR DESCRIPTION
**Pull request by LukeKyle**
[comment]: <I've created a new QA module for the tpc that I would like to add to the current list of modules.> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <Currently, the module creates two simple histograms that mark the number of hits and ADC values across all channels in the tpc. These histograms are only starting points and are likely to be replaced or modified in the near future.> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
I sent you an invite @LukeKyle to join the repo, accept it and then we can start the CI

**Review by osbornjd — CHANGES_REQUESTED** [review]
We're trying to organize all the QA together here:
https://github.com/sPHENIX-Collaboration/coresoftware/tree/master/offline/QA
Can you put this module in a new `Tpc` directory there?

Also you should interface this module with the Fun4AllHIstoManager in the way the other QA modules do, so that all QA histograms that are produced in a single job get dumped into the same file. See [here](https://github.com/sPHENIX-Collaboration/coresoftware/blob/fefd0eb0a06c0c1cac3a1382719667171f6c99bc/offline/QA/Calorimeters/CaloValid.cc#L655) for how histograms are created and added to the histo manager, [here](https://github.com/sPHENIX-Collaboration/coresoftware/blob/fefd0eb0a06c0c1cac3a1382719667171f6c99bc/offline/QA/Calorimeters/CaloValid.cc#L481) is an example of how they are obtained. Then all the histo management is performed for you with [this](https://github.com/sPHENIX-Collaboration/macros/blob/10a432046e8eba3f1800ee0d581cc970051dbb2d/CaloProduction/Fun4All_Year1.C#L309-L311).

Feel free to let me know if you need help or have questions regarding any of this

**Comment by LukeKyle** [comment]
Sure, I'll move the module and then work on interfacing it with the HistoManager. I'll let you know if any questions come up!

**Comment by osbornjd** [comment]
Oh and one other comment, you need to add the new module to the Makefile.am in the package so that it is included in the compilation

**Comment by pinkenburg** [comment]
When I went with Luke over the code I saw that someone had move reconstruction modules into the tpc_io library which then will introduce bad library dependencies when just reading DSTs. I just pushed a change to the Makefile.am which corrects this (should not require any macro changes). Also - from the porting to gcc12 we still had a lot of special warning suppressions in the configure.ac which are not needed anymore

**Comment by pinkenburg** [comment]
The build failure looks like libtrack_reco depends on the wrong library, I'll look into this a bit later. Maybe in the meantime you can add your module to the Makefile.am so we get this done

**Comment by LukeKyle** [comment]
I updated my Makefile.am and made a new Tpc directory in QA. I pushed the new changes to the pull request, but I'm not sure if I did it correctly. I tried updating my local Makefile.am to have Chris' changes before adding my module but I wasn't sure how to do it

**Comment by osbornjd** [comment]
I moved things around, fixed the makefiles and added the package to our build. Lets see what jenkins says now

**Comment by osbornjd** [comment]
Something went haywire in the merge so I fixed the makefile to match the changes that Chris fixed

**Pull request merged**
