### PR TITLE
HF updates

### PR DESCRIPTION
**Pull request by cdean-github**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

Made updates to three packages:

KFParticle: Updated truth matching to use proper global vertex matching. There was also an error where it couldn't find a truth vertex when a different track map was used. I added a new check to get the truth vertex based on the PHG4Particle parent ID

DecayFinder: Bug fix where the decay products from intermediate resonances weren't added to the output node

HFTrackEfficiency: Found instances (maybe 7% of events) where there are merged tracks. Discovered in a Bs0 -> J/psi (-> ee) K_S0 (-> pi pi) study where some truth particles are so collinear (I assume) that they merge into a single track. This biased the heavy flavor selected track map (I wanted 4 tracks but 7% of the time I got 3, or 2). A fully reconstructed decay is now tagged when the number of unique tracks equals the number of required tracks, not the number of tracks matched as was done previously.

@jdosbo do we want to know how many merged tracks we find?

I also ran clang-tidy on these 3 packages
[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
> Found instances (maybe 7% of events) where there are merged tracks. Discovered in a Bs0 -> J/psi (-> ee) K_S0 (-> pi pi) study where some truth particles are so collinear (I assume) that they merge into a single track. This biased the heavy flavor selected track map (I wanted 4 tracks but 7% of the time I got 3, or 2). A fully reconstructed decay is now tagged when the number of unique tracks equals the number of required tracks, not the number of tracks matched as was done previously.

Just making sure I understand exactly what is being described here - what you are saying is that at truth level there are events where two truth particles are so collinear that they are reconstructed as a single track? And this biases the reconstruction efficiency because there weren't the same number of tracks reconstructed as are actually in the decay chain?

**Comment by cdean-github** [comment]
> > Found instances (maybe 7% of events) where there are merged tracks. Discovered in a Bs0 -> J/psi (-> ee) K_S0 (-> pi pi) study where some truth particles are so collinear (I assume) that they merge into a single track. This biased the heavy flavor selected track map (I wanted 4 tracks but 7% of the time I got 3, or 2). A fully reconstructed decay is now tagged when the number of unique tracks equals the number of required tracks, not the number of tracks matched as was done previously.
> 
> Just making sure I understand exactly what is being described here - what you are saying is that at truth level there are events where two truth particles are so collinear that they are reconstructed as a single track? And this biases the reconstruction efficiency because there weren't the same number of tracks reconstructed as are actually in the decay chain?

Yes, that's what it seems like (or something else is going on but my best bet is merging):
```
---------------- DecayFinderNode: myFinder_DecayMap information ----------------
Particle embedding ID: 1, particle barcode: 114, particle PDG ID: 531
Particle embedding ID: 1, particle barcode: 239, particle PDG ID: 11
Particle embedding ID: 1, particle barcode: 240, particle PDG ID: -11
Particle embedding ID: 1, particle barcode: 193, particle PDG ID: 443
Particle embedding ID: 1, particle barcode: 248, particle PDG ID: 211
Particle embedding ID: 1, particle barcode: 249, particle PDG ID: -211
Particle embedding ID: 1, particle barcode: 241, particle PDG ID: 310
--------------------------------------------------------------------------------------------------
../HFTrackEfficiency.cc: PHG4ParticleSvtxMap found, truth matching will be more accurate
GenParticle: 114 ID:531 (P,E)=-11.391,-4.273,-5.488,14.386 Stat:2 PV:-73 EV:-109 Pol:(0.000,0.000) F:0
GenParticle: 239 ID:11 (P,E)=0.078,-0.242,0.257,0.361 Stat:1 PV:-131 EV:0 Pol:(0.000,0.000) F:0
SvtxTrack_v4 Object id: 11 vertex id: 0 charge: -1 chisq: 600.426 ndf:66 nstates: 34 
(px,py,pz) = (0.090,-0.251,0.267)
(x,y,z) = (-0.684,-0.245,-14.490)

GenParticle: 240 ID:-11 (P,E)=-7.461,-1.138,-4.863,8.979 Stat:1 PV:-131 EV:0 Pol:(0.000,0.000) F:0
SvtxTrack_v4 Object id: 10 vertex id: 0 charge: 1 chisq: 66.100 ndf:90 nstates: 46 
(px,py,pz) = (-7.389,-1.131,-4.825)
(x,y,z) = (0.002,-0.016,-14.224)

GenParticle: 248 ID:211 (P,E)=-2.243,-1.676,-0.700,2.889 Stat:1 PV:-136 EV:0 Pol:(0.000,0.000) F:0
SvtxTrack_v4 Object id: 30 vertex id: 0 charge: 1 chisq: 88.556 ndf:48 nstates: 25 
(px,py,pz) = (-2.155,-1.864,-0.738)
(x,y,z) = (-1.662,1.922,-10.300)

GenParticle: 249 ID:-211 (P,E)=-1.765,-1.218,-0.182,2.157 Stat:1 PV:-136 EV:0 Pol:(0.000,0.000) F:0
SvtxTrack_v4 Object id: 30 vertex id: 0 charge: 1 chisq: 88.556 ndf:48 nstates: 25 
(px,py,pz) = (-2.155,-1.864,-0.738)
(x,y,z) = (-1.662,1.922,-10.300)

Adding track 11
Adding track 10
Adding track 30
Adding track 30
SvtxTrackMap_v2::insertWithKey - duplicated key. track not inserted
SvtxTrackMap_v2: size = 3
```

**Comment by osbornjd** [comment]
Interesting, we should study these tracks in more detail to find out if it is happening at the clustering or seeding stage. Those aren't particularly high pT either. It would be useful to know how many there are to know whether or not this is a big problem, I guess it is nontrivial if it is affecting 7% of decays

**Comment by cdean-github** [comment]
> Interesting, we should study these tracks in more detail to find out if it is happening at the clustering or seeding stage. Those aren't particularly high pT either. It would be useful to know how many there are to know whether or not this is a big problem, I guess it is nontrivial if it is affecting 7% of decays

I could try and do a more in depth study. 7% seems significant but if these are events where we could never actually reco the decay (as a track is too low in pT or out the detector geometry) then it's 7% we've already lost. [I have the generator in the analysis repo so it's easy to launch and study](https://github.com/sPHENIX-Collaboration/analysis/tree/master/HF-Particle/KFParticle_sPHENIX/b_hadron_generator). These are the clusters of track 30
```
Silicon clusters 

Tpc + TPOT clusters 
152288957516742658, 152570432493453313, 152851907470163970, 153133382446874626, 153414857423585282, 153696332400295938, 153977807377006594, 154822232307138563, 155103707283849217, 155385182260559875, 155666657237270529, 155948132213981188, 156229607190691843, 156511082167402499, 156792557144113154, 157074032120823813, 157355507097534467, 157636982074245121, 157918457050955779, 158199932027666433, 158481407004377090, 158762881981087760, 159044356957798412, 159325831934509075, 
````

**Comment by osbornjd** [comment]
Probably the TPC seeder gets confused then as it looks like a TPC only track where it didn't find nearly all the layers in the TPC. It probably combined segments from the two tracks inadvertently - in any case, we should probably study it in more depth if it happens with some nontrivial frequency

**Comment by cdean-github** [comment]
> Probably the TPC seeder gets confused then as it looks like a TPC only track where it didn't find nearly all the layers in the TPC. It probably combined segments from the two tracks inadvertently - in any case, we should probably study it in more depth if it happens with some nontrivial frequency

Sounds like I have a new meeting to join on Friday morning

**Pull request merged**
