### PR TITLE
fix: suppress verbosity

### PR DESCRIPTION
**Pull request by osbornjd**
@hupereir any objection to suppressing this with a verbosity call? it can fill up logfiles

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by hupereir** [comment]
@osbornjd This message tells you that the TPOT data is unuseable essentially. What can happen is that you get it a few times before finally a proper reference is found and the run can be reconstructed.
If it fills the log, it means that the entire run is unuseable for TPOT and TPOT should then not be included in the reconstruction. (essentially all runs before 45288 ) 

So all in all, I would rather not hide this message behind verbosity because  this is really a problem. (and if the data is reconstructible, the message should not appear, or only a few times).

What I can do is set a limit to the number of times it happens and then abort, if you prefer.

**Comment by osbornjd** [comment]
> What I can do is set a limit to the number of times it happens and then abort, if you prefer.

Sure, that would be nice as if the run is not reconstructible for TPOT then we should just not continue on. This would also suggest we should separate the event combining production into separate jobs though, as a run that is bad for TPOT may not be for some other subsystem. Perhaps we should punt this to when some further development on that front happens.

**Comment by hupereir** [comment]
could you point me to one or several run numbers for which this message has been flooding the logs ?

**Comment by osbornjd** [comment]
Takao reported this, let me discuss with him

**Pull request closed without merging**
