### PR TITLE
Ditch phtpctracker

### PR DESCRIPTION
**Pull request by pinkenburg**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
This PR removes PHTpcTracker from our build and cleans out the remnants of HelixHough
[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
We should poll the tracking group to make sure none of these are still actively used. For example, I think Hugo still uses the genfit track fitter (but not the propagator, he can correct me if I'm wrong).

**Comment by pinkenburg** [comment]
Point taken - just want to see if this goes through. None of the removed code was in the Makefile, so we haven't been building any of this. If there is code still in use - we should add it back to the Makefile.am so it gets compiled and tested

**Comment by osbornjd** [comment]
Okay fair - that seems likely then that nobody is using it 🤣

**Comment by pinkenburg** [comment]
If it turns out I removed too many sources - we can put them back

**Pull request merged**
