### PR TITLE
Cluster container

### PR DESCRIPTION
**Pull request by hupereir**
[comment]: <> (Please tell us something about this pull request)
This pull request introduces a new cluster container that stores clusters in a std::vector rather than a std::map
Performances are discussed here: https://indico.bnl.gov/event/15452/contributions/62759/attachments/40662/67929/talk.pdf
Also cleaned up TPC clusterizer and TPC simple clusterizer, and used std::thread instead of pthread.
The former is more modern, does the same under the hood, but should be more future proof (and platform independent, which is irrelevant here)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
The clang error is from xpload - Dmitri changed an interface. Falling back to the previous xpload version

**Comment by hupereir** [comment]
Hi @pinkenburg 
Is this also related to why I can't seem to run anything locally lately (for the last few hours) ? 
All I get is: 
/phenix/u/hpereira/sphenix/src/macros/common/G4_Bbc.C:14:1: fatal error: 'libg4bbc.so' file not found
R__LOAD_LIBRARY(libg4bbc.so)
^
/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/root-6.24.06/root-6.24.06/build/include/Rtypes.h:456:35: note: expanded from 
macro 'R__LOAD_LIBRARY'
# define R__LOAD_LIBRARY(LIBRARY) _R_PragmaStr(cling load ( #LIBRARY ))
                                  ^
/gpfs/mnt/gpfs02/sphenix/user/phnxbld/workarea/sPHENIX_SL7.3/gcc-8.3/root-6.24.06/root-6.24.06/build/include/Rtypes.h:455:26: note: expanded from 
macro '_R_PragmaStr'
# define _R_PragmaStr(x) _Pragma(#x)
                         ^
<scratch space>:9:29: note: expanded from here
 cling load ( "libg4bbc.so" )
                            ^
cling::DynamicLibraryManager::loadLibrary(): libxpload.so.0.7.3: cannot open shared object file: No such file or directory
cling::DynamicLibraryManager::loadLibrary(): libxpload.so.0.7.3: cannot open shared object file: No such file or directory
Warning in <TInterpreter::TCling::RegisterModule>: Problems in compiling forward declarations for module libROOTNTuple: '

**Comment by hupereir** [comment]
Forget it. A complete recompilation of my local libs somehow fixed it.

**Comment by pinkenburg** [comment]
> Forget it. A complete recompilation of my local libs somehow fixed it.

I switched briefly to a new xpload version (0.8.1) which then gave the compilation warning with clang and I fell back to 0.7.3. You must have compiled against 0.7.3 and picked up a new build against 0.8.1. Now we are back at 0.7.3 and you will likely get a complaint that 0.8.1 is missing and have to recompile

**Pull request merged**
