### PR TITLE
Silicon+TPOT fit update

### PR DESCRIPTION
**Pull request by osbornjd**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This PR recovers the performance of the silicon+TPOT fit. It removes the use of the directed fitter and just uses the standard Acts::KF for the fit, which simplifies the code. The attached plot shows the performance of the silicon only fit (left) vs. silicon + TPOT fit (right) for single tracks.
[fit_tpot_silicon.pdf](https://github.com/sPHENIX-Collaboration/coresoftware/files/11100983/fit_tpot_silicon.pdf)

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by hupereir** [comment]
Just one precision about "This PR recovers the performance of the silicon+TPOT fit"
It is not enough to just look at the momentum resolution inside TPOT acceptance to see how "recovered" the performances of the TPOT and Silicon fit are. One must really look into the residuals between the extrapolated track parameters to the TPC layers and the TPC clusters. 
In any case: this cleanup of the code is more than welcome. I'll look into the residuals as soon as this gets through.

**Comment by osbornjd** [comment]
> Just one precision about "This PR recovers the performance of the silicon+TPOT fit" It is not enough to just look at the momentum resolution inside TPOT acceptance to see how "recovered" the performances of the TPOT and Silicon fit are. One must really look into the residuals between the extrapolated track parameters to the TPC layers and the TPC clusters. In any case: this cleanup of the code is more than welcome. I'll look into the residuals as soon as this gets through.

I agree, I just meant that this at least confirms that with the latest builds the silicon+TPOT fit works (which wasn't clear to me at the time...). I agree we should also study the residuals.

**Comment by hupereir** [comment]
Also, which cluster version did you use to get these plots ? 
Currently, PHTpcResidual crashes if you select v5, as far as I can tell (I have a pending fix which I plan to push today)

**Comment by osbornjd** [comment]
I used v5. I haven't tested anything in tpccalib, this is just an update to the fitting itself. So the plot I made was just output in the evaluator after running single pions into the TPOT acceptace straight out of PHActsTrkFitter

**Comment by hupereir** [comment]
> I used v5. I haven't tested anything in tpccalib, this is just an update to the fitting itself. So the plot I made was just output in the evaluator after running single pions into the TPOT acceptace straight out of PHActsTrkFitter

Ok Makes sense.
For what its worth, checkign the residuals with cluster v5 and fixed PHTpcResiduals does give the right residuals in the TPC, (already before this pull request). This was not the case with cluster v4 (hence the question), which led me to claim that the distortion reconstruction code was currently broken. Bottom line: it is not. 
I'll create a pull request for fixing PHTpcResiduals, and test again with the modified ActsTrkFitter.

**Comment by osbornjd** [comment]
Okay that sounds good, I think we have more to understand about the parameterized cluster uncertainties.

Not sure why this is bombing out in jenkins but I will debug

**Comment by osbornjd** [comment]
Successful associated QA build with macros PR 607

**Pull request merged**
