### PR TITLE
Padplane readout phi

### PR DESCRIPTION
**Pull request by mohaas33**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)
The PR includes reading gain maps for TPC, obtained from scanning modules during production.
[ADCs will have different weight then before]: <https://indico.bnl.gov/event/18865/contributions/74754/attachments/46935/79566/eshulga_DC_04102023.pdf>

### CODE REVIEW

**Comment by pinkenburg** [comment]
The clang failure is my doing, forget about this. The valgrind leak seems to be that the histograms in the gain[] array are not deleted (cloning makes a copy). Small trick instead of clining you can use this:
Hist->SetDirectory(nullptr);  // rootism: this needs to be set otherwise histo vanished when closing the file
but you still need to delete the hist in the dtor

**Comment by pinkenburg** [comment]
Now that the QA went through - there are massive changes. We should have a closer look at this. I converted this PR to draft so it doesn't get merged accidentally

**Comment by osbornjd** [comment]
@pinkenburg is this last jenkins build a result of this weird hcal overlap that pops up occasionally?

**Comment by pinkenburg** [comment]
No - it crashes when deleting a histogram from the gainmap. I assume it's a dangling pointer now that the file is not loaded

**Pull request closed without merging**
