### PR TITLE
New Jet Evaluator Objects and SubsysReco

### PR DESCRIPTION
**Pull request by mccumbermike**
The jet evaluator runs and appears to produce valid output (I'll need a pythia install to be 100% sure). We can talk about this one at Tuesday's meeting as the merge also deprecates the old tracking and calorimeter evaluators in order to simplify the build dependencies. I've already removed these from the macros, but somewhere I'm sure someone hasn't yet pulled from macros.git to complete the swap in their local directory. I can back out those commits if it is felt there is value in keeping these around longer.

EDIT: This merge also includes the RawTower id patch already.

### CODE REVIEW

**Comment by mccumbermike** [comment]
Now that the tower ids are patched, we can pull in this branch.

**Comment by mccumbermike** [comment]
I'll update the G4_Jets.C macro with the evaluator call when we get the
next new build out into the wild.

Mike

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by pinkenburg** [comment]
Hi Mike,

the next build is already done - I kicked one off right after the merge

Chris

On 09/08/2015 02:58 PM, Michael P. McCumber wrote:
> I'll update the G4_Jets.C macro with the evaluator call when we get the
> next new build out into the wild.
>
> Mike
>
> --
> Michael P. McCumber, PhD
> Los Alamos National Laboratory
> 505-709-8161
>
> On Tue, Sep 8, 2015 at 12:40 PM, Jin Huang <notifications@github.com> 
> wrote:
>
> > Merged #34 
> <https://github.com/sPHENIX-Collaboration/coresoftware/pull/34>
> > .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/sPHENIX-Collaboration/coresoftware/pull/34#event-404000807>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sPHENIX-Collaboration/coresoftware/pull/34#issuecomment-138670359>.
>


-- 

*********************************************************

Christopher H. Pinkenburg      ; pinkenburg@bnl.gov

Brookhaven National Laboratory ; phone: (631) 344-5692
Physics Department Bldg 510 C  ; fax:   (631) 344-3253
Upton, NY 11973-5000

http://www.phenix.bnl.gov/~pinkenbu/

*********************************************************

**Comment by mccumbermike** [comment]
Okay, I've updated the macro area. This merge is complete.

**Pull request merged**
