### PR TITLE
Jetbase 2

### PR DESCRIPTION
**Pull request by david-stewart**
[comment]: <> (Please tell us something about this pull request)

This is the first part of a process requested by the jet group.

This pull request splits most functionality of the library `simulation/g4simulation/g4jets` to `offline/packages/jetbase`.
The g4jets library then pulls support from jetbase. The code has the same functionality as before and just require that client code load the `jetbase` library and refer to the `jetbase` headers instead of `g4jet` (except for the objects `JetHepMCLoader` and `TruthJetInput` which remain in `g4jet`)

The motivation is to removed simulation libraries dependencies from the jet reconstruction.

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by david-stewart** [comment]
Hi @pinkenburg and experts, this draft pull request moves the non-simulation part of the jet reconstruction code into a new directory at `offline/packages/jetbase` with a correspondingly named library. Jenkins is failing because it doesn't appear to know to build the new library in `jetbase` first before asking for it in `g4jets`. I suspect this is a matter of updating the list of compilation codes for Jenkins.

**Comment by david-stewart** [comment]
see for example [this Jenkins error](https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-Master-gcc12/1137//gcc/new/)

**Comment by osbornjd** [comment]
I just added it, let's try jenkins again

**Comment by david-stewart** [comment]
thanks @osbornjd  -- should I re-push it in order to trigger jenkins a second time?

**Comment by osbornjd** [comment]
Go for it, just do `git commit --allow-empty -m "trigger jenkins"`

**Comment by david-stewart** [comment]
Hi @osbornjd , I fixed the issues in coresoftware, but now Jenkins is also testing it against `tutorials/myjetanalysis/src/MyJetAnalysis.cc`. I will have to fix those, too, and somehow tell Jenkins to concurrently test both repositories. Is there a list of all the analyses that are tested that I need to update?

**Comment by osbornjd** [comment]
@blackcathj can we momentarily disable the tutorials repo from the Jenkins builds? In the meantime @david-stewart make a PR in the tutorials repo for the changes corresponding to this PR and then we will merge everything together once it's time to do so

**Comment by osbornjd** [comment]
Okay, I think I disabled them in jenkins. @david-stewart push an empty commit to retrigger jenkins. You will need to make sure that `myjetanalysis` and `AnaTutorial` compile with your changes in the tutorials repo, these are the only extra packages that are built with jenkins.

**Comment by david-stewart** [comment]
ok -- I'll update `myjetanalysis` and `AnaTutorial` and post here when that is done

**Comment by david-stewart** [comment]
in the mean time I have pushed the empty commit

**Comment by pinkenburg** [comment]
the readback macro uses libg4dst.so which is linked against all i/o libraries for convenience. It is build in simulation/g4simulation/g4dst. The jetbase i/o lib is missing so it runs into classes on the dst during readback it doesn't know about

**Comment by david-stewart** [comment]
Thanks -- I'll adjust libg4dst to try and fix it

**Comment by pinkenburg** [comment]
looks good - no changes in jenkins. Let me merge this so the tutorial can be updated

**Comment by david-stewart** [comment]
Hi @pinkenburg  -- I think that's ok; but I haven't cleared it with the jet group yet;
It looks like I may have to ask for forgiveness rather than permission, lol

**Comment by david-stewart** [comment]
The work was assigned by the JS group, I just hadn't gotten their clearance on this part; but it is a pretty benign change, so should be ok

**Pull request merged**
