### PR TITLE
Adding pointers protection

### PR DESCRIPTION
**Pull request by antoniocosilva**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

Adding protection against null pointers (towerinfo and towergeom)

### CODE REVIEW

**Comment by pinkenburg** [comment]
We have to be careful with just protecting the code from crashing. The first check protect against missing towers which may be a possibility in the future, but right now this is an indication that something is severely wrong somewhere.
The second check is for the geometry pointer. If this one is null we are in severe trouble and you would just drop acceptance without realizing. There should be at least a printout.
In general - I do prefer code to crash and burn rather than to continue silently when fatal errors are encountered and the results are likely tainted

**Comment by antoniocosilva** [comment]
As far as I could see, the towers are always there and not crashing anything. I will add a print out there.
As for the geometry pointers, I agree that this could be a serious issue. At this moment, I'm still not sure why the pointer would not be found. I will ask Tim if he saw something like this happening too.

**Comment by antoniocosilva** [comment]
I think I found the issue. I will cross-check it with Tim.

**Comment by antoniocosilva** [comment]
Hi Cris, Tim made a PR to fix the bug that was making the geometry objects to crash the code. I think I agree with you that sometimes it's better if the code crash and burn so that we know that something is not quite right, so we should probably not include these protections and cancel this PR.

**Pull request closed without merging**
