### PR TITLE
Jet DST skimmer

### PR DESCRIPTION
**Pull request by Shuonli**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This is the initial commit to the module for making the slimed(skimmed?) DST. Where it will search for max Jet energy and EMCal cluster energy per event and only keep the event that contains high energy jets/clusters.

I think it will also good to have the background event (beam background) rejection implemented in this. I have left a place holder here.

## TODOs (if applicable)

Implement the Beam background ID function.

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
Can I suggest that we organize this differently? Let's have a directory structure that looks like
offline
-- packages
---- Skimmers
------- Jets
---------- JetSkimmer.cc/h/makefile/etc

Then we can make other directories for different types of skimmers

**Comment by bseidlit** [comment]
@osbornjd  Don't we want  "slimmer" not "skimmer"?  We are taking out events not removing information for each event.

**Comment by osbornjd** [comment]
I don't think we ever decided on a specific name - every collaboration has their own but I don't think we came to a conclusion. Slimmer and skimmer could in principle refer to the same thing - either you slim the DST down to only include the events you want or you are skimming the larger DST to write out only the ones you want

**Comment by eumaka** [comment]
Sorry I missed the last software meeting. What ever name is decided, these DSTs are meant to skip events that don't meet a certain cut, e.g. jet pT etc...?

**Comment by osbornjd** [comment]
They're intended to be used to write out smaller DSTs that meet certain criteria

**Comment by bseidlit** [comment]
Okay, I don't have strong opinions.  I think in phenix they called them mini DSTs.

**Comment by bseidlit** [comment]
It was decided in the software meeting to call it a skimmer.

**Pull request merged**
