### PR TITLE
SvtxHitEval: truth matching with trkrid as an additional argument

### PR DESCRIPTION
**Pull request by hrjheng**
[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
Does this replace https://github.com/sPHENIX-Collaboration/coresoftware/pull/1708?

**Comment by hrjheng** [comment]
Yes, this is the same #1708 except that I merged this branch with master (with HelixHough removed).

**Comment by osbornjd** [comment]
You can always do a `git pull origin master` when you have your modified feature branch checked out and then push to that feature branch name on your fork, which will update the original pull request. As in:
```
git checkout my_feature_branch
git pull origin master
git push fork my_feature_branch
```
Then you don't need to open a new pull request and all your modifications will stay on that feature branch (it's fine this time, just a suggestion for future contributions).

**Review by osbornjd — APPROVED** [review]
From 1708 these functions give the expected performance for the MVTX, were they also tested with the other tracking detectors? These I guess aren't actually used in any of the default relation/association tracing so there isn't a problem merging them - I am just asking if the functionality was tested with all tracking detectors or just the mvtx

**Comment by hrjheng** [comment]
I ran a quick check for INTT and TPC, plots for g4hit distribution (X and Y) are attached.
For INTT:
Screen Shot 2022-10-24 at 16 19 46
For TPC:
Screen Shot 2022-10-24 at 16 30 30

**Comment by osbornjd** [comment]
Thanks! Lets merge it

**Pull request merged**
