### PR TITLE
Fix TPC volume id detection in ActsTrkFitter

### PR DESCRIPTION
**Pull request by hupereir**
Since the micromegas geometry reimplementation in ACTS, the main TPC volume ID has changed from 14 to 12, likely  because of how ACTS handles Geant volumes internally when converting to ACTS geometry. 

This breaks the volume-id based identification of TPC surfaces in ActsTrkFitter.

Rather than updating the hard-coded volume id used for this identifiation, an std::set is used to store TPC relevant volume IDs. It is filled from TPC surfaces when calling GetNodes and is used for TPC surfaces identifiaction.

This is essentially the same change as in https://github.com/sPHENIX-Collaboration/coresoftware/pull/1194, but for the TPC

Following suggestion from Joe, the std::sets for Micromegas and TPC are moved to ActsSurfaceMap, and filled in MakeActsGeom.
Two convenience functions are added to ActsSurfaceMaps, namely isTpcSurface and isMicromegasSurface. 
They are used in PHActsTrkFitter to identified the relevant surfaces.

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by osbornjd** [comment]
There aren't any other places as far as I know; I just did a quick search and don't see anything. A lot of that was actually cleaned up when moving away from `PHActsSourceLinks`. We can stay with this implementation for now, I think the future best choice would be to actually have these values created and stored in the `ActsTrackingGeometry` object which is passed around on the node tree and created in `MakeActsGeometry`. That can wait for a future PR though, I would say.

**Comment by hupereir** [comment]
> There aren't any other places as far as I know; I just did a quick search and don't see anything. A lot of that was actually cleaned up when moving away from `PHActsSourceLinks`. We can stay with this implementation for now, I think the future best choice would be to actually have these values created and stored in the `ActsTrackingGeometry` object which is passed around on the node tree and created in `MakeActsGeometry`. That can wait for a future PR though, I would say.

Hi Joe, 
I agree that ActsTrackingGeometry is the right place to do this.

**Comment by osbornjd** [comment]
Hi Hugo, there is something weird going on in the QA for high occupancy especially in the vertexing. Can you run a test locally with some hijing job and see if you see some similar behavior?

**Comment by hupereir** [comment]
> Hi Hugo, there is something weird going on in the QA for high occupancy especially in the vertexing. Can you run a test locally with some hijing job and see if you see some similar behavior?

Hi Joe,
Do you refer to #clusters per tracks and tracking efficiency vs eta ? 
If yes, I agree it looks weird, but it is not new to this commit. 
See QA plots for e.g. https://github.com/sPHENIX-Collaboration/coresoftware/pull/1204
Or did I miss additional differences to the plots from commit above ?

**Comment by hupereir** [comment]
It seems like the fist commits that show the said changes are 
https://github.com/sPHENIX-Collaboration/coresoftware/pull/1202
And 
https://github.com/sPHENIX-Collaboration/coresoftware/pull/1203

First one is particulary strange, since it is completely unrelated to any tracking change as far as I can tell

**Comment by osbornjd** [comment]
I was referring to the DCA and vertexing plots [here](https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-high-occupancy-qa-1030-test-tracking_Event50_Sum10/QA-vertexing.ipynb). The clusters per track is an ongoing development I think with the CA seeder.

**Comment by hupereir** [comment]
> I was referring to the DCA and vertexing plots [here](https://nbviewer.jupyter.org/github/sPHENIX-Collaboration/QA-gallery/blob/jenkins-sPHENIX-test-tracking-high-occupancy-qa-1030-test-tracking_Event50_Sum10/QA-vertexing.ipynb). The clusters per track is an ongoing development I think with the CA seeder.

Unless I missed something, these one two (the high-occupancy DCA plots) seem broken since https://github.com/sPHENIX-Collaboration/coresoftware/pull/1201

(also, this PR change should really have no impact on any QA plot, since it only affects SC_CALIBMODE = true code path)

**Comment by osbornjd** [comment]
Ah, we apparently missed that one then... Looks like I have to do some debugging

**Pull request merged**
