### PR TITLE
XY and Z vertex modules are updated significantly, and minor debugging

### PR DESCRIPTION
**Pull request by hahahachiya**
1) XY and Z vertex modules are updated significantly,
2) update to handle 0 size of rawhit container in InttCombinedRawDataDecoder

[comment]: <> (Please tell us something about this pull request)

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by pinkenburg** [comment]
Please follow our include convention - this is really important, otherwise a local change will not be picked up properly leading to a mix of includes when compiling a package locally:
https://wiki.sphenix.bnl.gov/index.php/Codingconventions#Include_Files

**Review by osbornjd — COMMENTED** [review]
Some of this code is really reconstruction code (e.g. InttZVertexFinder) while some of it is really analysis code, from what I can tell (e.g. a lot of the code in INTTXYvtx.h). Is it possible we could split this up into the code that is actually reconstruction code and then we put the analysis code in a dedicated analysis repository?

**Comment by hahahachiya** [comment]
INTTZvtx and INTTXYvtx are the core parts of the reconstruction code. but QA parts are also included. Yes I will split them.

**Comment by hahahachiya** [comment]
Current module can reconstruct the z-vertex well but also contains the some QA code.   It takes time to separate the reconstruction part and QA part. If it is OK, it would be good to accept the current code for now. I will split the code soon (not so late).

**Pull request merged**
