### PR TITLE
MVTX timing using strobe pulses

### PR DESCRIPTION
**Pull request by cdean-github**
[comment]: <> (Please tell us something about this pull request)
First version of MVTX timing using strobe pulses.

This draft is for the review and alterations of Yasser, @blackcathj @adfrawley @jdosbo 

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [x] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

This adds an alternate timing mode for the MVTX where a random alpide timing window is generated from an approximation of the start and end time distributions as a function of number of electrons deposited.

A strobe pulse start is randomly generated from a uniform distribution of the sum of strobe width and strobe separation (separation is the difference between falling and rising edges!!!). 

The hit must land in the following range to be accepted:

geant4 hit time + alpide pulse start time < strobe start + strobe width < geant4 hit time + alpide pulse start time + alpide pulse end time

The alpide pulse start and end time are **different** for each hit. The strobe start time is the **same** for each event

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

We should figure out how to make the number of electrons released a function of the deposited energy as measured by Geant4. The initial work for this is done, we just need a conversion factor as initial tests gave too large a number of electrons. The number of electrons defines the alpide pulse window

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

## Links to other PRs in macros and calibration repositories (if applicable)

This should be backward compatible but lines can be added to macros/common/G4_Mvtx.C to test this:

```c++
  PHG4MvtxHitReco* maps_hits = new PHG4MvtxHitReco("MVTX");
  maps_hits->Verbosity(verbosity);
  maps_hits->use_strobed_mode(true);
```
the strobe properties are defaulted to a width of 5us and separation of 0us. They can be altered from the function:
```c++
void set_strobe_properties(double width, double separation) {m_strobe_width = width; m_strobe_separation = separation;}
```

### CODE REVIEW

**Comment by sPHENIX-GitHub-l** [comment]
Hi Cameron,

Do I correctly read the comment to say that the strobe separation is 0 microseconds? I thought that the strobe separation (end of one to the beginning of the next) was expected to be more like 5 microseconds?

Thanks
Tony
________________________________
From: sPHENIX-GitHub-l ***@***.***> on behalf of cdean-github ***@***.***>
Sent: Friday, March 25, 2022 6:01 PM
To: sPHENIX-Collaboration/coresoftware ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Sphenix-github-l] [sPHENIX-Collaboration/coresoftware] MVTX timing using strobe pulses (PR #1451)


First version of MVTX timing using strobe pulses.

This draft is for the review and alterations of Yasser, @blackcathj<https://urldefense.com/v3/__https://github.com/blackcathj__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01nSw9Pa5$> @adfrawley<https://urldefense.com/v3/__https://github.com/adfrawley__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01vySVyB5$> @jdosbo<https://urldefense.com/v3/__https://github.com/jdosbo__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01uGVZ3Fp$>

Types of changes

  *    Bug fix (non-breaking change which fixes an issue)
  *    New feature (non-breaking change which adds functionality)
  *    Breaking change (fix or feature that would cause existing functionality to not work for users)
  *    Requiring change in macros repository (Please provide links to the macros pull request in the last section)
  *    I am a member of GitHub organization of sPHENIX Collaboration<https://urldefense.com/v3/__https://github.com/orgs/sPHENIX-Collaboration/people__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01ru07vbG$>, EIC, or ECCE (contact Chris Pinkenburg to join)

What kind of change does this PR introduce? (Bug fix, feature, ...)

This adds an alternate timing mode for the MVTX where a random alpide timing window is generated from an approximation of the start and end time distributions as a function of number of electrons deposited.

A strobe pulse start is randomly generated from a uniform distribution of the sum of strobe width and strobe separation (separation is the difference between falling and rising edges!!!).

The hit must land in the following range to be accepted:

geant4 hit time + alpide pulse start time < strobe start + strobe width < geant4 hit time + alpide pulse start time + alpide pulse end time

The alpide pulse start and end time are different for each hit. The strobe start time is the same for each event

TODOs (if applicable)

We should figure out how to make the number of electrons released a function of the deposited energy as measured by Geant4. The initial work for this is done, we just need a conversion factor as initial tests gave too large a number of electrons. The number of electrons defines the alpide pulse window

Links to other PRs in macros and calibration repositories (if applicable)

This should be backward compatible but lines can be added to macros/common/G4_Mvtx.C to test this:

  PHG4MvtxHitReco* maps_hits = new PHG4MvtxHitReco("MVTX");
  maps_hits->Verbosity(verbosity);
  maps_hits->use_strobed_mode(true);

the strobe properties are defaulted to a width of 5us and separation of 0us. They can be altered from the function:

void set_strobe_properties(double width, double separation) {m_strobe_width = width; m_strobe_separation = separation;}

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01m58cT1L$>

Commit Summary

  *   f9c5409<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451/commits/f9c54094444899bc1d1c62a5f91688e22cfa92dd__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01mIj16P7$> First version of strobed MVTX
  *   b5300ab<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451/commits/b5300ab2355f9d701aa1b91934a49894de5f9b17__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01gBm5M82$> Fixed strobe generation window

File Changes

(3 files<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451/files__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01kkO5GNp$>)

  *   M simulation/g4simulation/g4mvtx/Makefile.am<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451/files*diff-885931e425fc2dc5468c2d21a23b34dacd29dbe8861a2350c956289c6df0bdaf__;Iw!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01pnQRpBM$> (1)
  *   M simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451/files*diff-433bf07540e4dafbed4806931069ae17fb322844b56db4f27b356db22678e29e__;Iw!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01k_6MjCL$> (59)
  *   M simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451/files*diff-eb8cc48add0b9056f85cb3ebd411085bf65fcc99b6b6fc167eb989c32ef8efb1__;Iw!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01v8YphDC$> (14)

Patch Links:

  *   https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451.patch<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451.patch__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01gLI0RIh$>
  *   https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451.diff<https://urldefense.com/v3/__https://github.com/sPHENIX-Collaboration/coresoftware/pull/1451.diff__;!!PhOWcWs!jkciOi5YTvPXuBpnNlgoNvlX5lU5dE1i7S23mQhjZKaeHmetwC9TFHQ01l6R3XfE$>

**Comment by cdean-github** [comment]
> Hi Cameron, Do I correctly read the comment to say that the strobe separation is 0 microseconds? I thought that the strobe separation (end of one to the beginning of the next) was expected to be more like 5 microseconds? Thanks Tony]

Hi Tony,

Yes, the default separation between the rising and fallings edges is set to 0s just now. We couldnt recall the exact value just now but I left it so this parameter can be set from the macro level. I thought it was better to let people see the logic of what would go into coresoftware because the strobe can be tuned in real life. Yassr, Jo and I can try to figure out what the realistic setting would be but this is reasonably close as we get ~99.8% coincidence, according to Yasser.

I made the strobe have two parameters, one is the pulse width and the other is the separation of falling and rising edges. This should allow us to simulate a "dead time" if we need it where there is no overlap between the digitiser and strobe.

Cheers,
Cameron

**Comment by adfrawley** [comment]
OK, thanks.

I guess the reason for not having zero separation time would be that it makes it very likely that the strobe would overlap the comparator output twice per signal, right?

BTW, does your simulation code produce multiple hits if that happens?

Thanks
Tony
________________________________

**Comment by cdean-github** [comment]
> OK, thanks. I guess the reason for not having zero separation time would be that it makes it very likely that the strobe would overlap the comparator output twice per signal, right? 

Yes, exactly. Zero separation is a little unrealistic but the separation should be small anyway so we can tweak this before the merge and continue tweaking at the macro level as needed.

>BTW, does your simulation code produce multiple hits if that happens? Thanks Tony

No, the code is just a basic logic check right now. I think this was Yasser's suggestion. We could expand that bit of the code to duplicate the hit if we simulate an overlap but I'd imagine we'd have to be careful with the hit keys to avoid a straight duplication there.

**Pull request closed without merging**
