### PR TITLE
Generic calorimeter tower description

### PR DESCRIPTION
**Pull request by blackcathj**
Generalized calorimeter description, which support both forward and central calorimeters, has been proposed by @nfeege for a few months, and we planned to review/merge it after pre-CDR. The idea also evolved through few iterations of discussions since @nfeege first proposed it in July. 

An updated version is proposed here for previewing. 

This pull request is NOT yet ready for merging. This request is to bring up this develop for discussion in the coming sPHENIX simulation meeting. We expect a few more changes after the meeting too.

### CODE REVIEW

**Comment by blackcathj** [comment]
Finished two tests:

1. A nightly-like build, including packages passing g4cemc and on. 

2. Tested with analyzing 100 8 GeV pi- data from the last production. The SVX track successfully matched with CEMC and HCALIN towers (note HCALIN has a know half tower shift in the azimuthal direction):
image

**Comment by nfeege** [comment]
I did a brief crosscheck of the crystal calorimeter (electron-going side for EIC): I used the particle gun to shoot 10 electrons at 10 GeV at direction eta = -2 and phi = PI/4. Magnetic field switched off. Attached plots show the energy deposited in single towers in the forward crystal calorimeter (after digitization and calibration, hence the large number of low energy 'noise' towers) at the x-y and eta-phi position of the towers given by RawTowerGeomv2 objects. Towers from all 10 electron events are included in the histograms.

The mean eta position in the second plot matches the particle gun eta. The phi position given by the hit towers is PI/2 larger then the phi angle passed to the particle gun. Could this be a difference in coordinate system definitions or is it an actual bug in the code?

tower_y_x_e_10gev_10events_fixeta_fixphi
tower_eta_phi_e_10gev_10events_fixeta_fixphi

**Comment by nfeege** [comment]
Update: I checked the forward electromagnetic calorimeter in the opposite direction, i.e. the positive-z direction (or hadron-going for EIC). Plot shows again eta and phi of hit towers and their energy for 10 GeV electrons at eta = 2 and phi = PI/4. Here, both eta and phi from the towers agree with eta/phi from the particle gun.

femc_tower_eta_phi_e_10gev_10events_fixeta_fixphi

**Comment by nfeege** [comment]
Fixed tower position sign flip for EEMC calorimeter. The parameter files for the mapping for the forward detectors now include a list of parameters for the calorimeter envelope size, orientation, and position in the global (detector) reference frame. Tower positions are given in the local, i.e. with respect to calorimeter envelope, reference frame. RawTowerBuilderByHitIndex updated to do the same transformation (tower local -> tower global) when reading the mapping files. First image shows FHCAL, FEMC, EEMC (from left to right) and Geant4 coordinate axes. The next three pictures are tower eta : phi in FHCAL, FEMC, and EEMC for 10 GeV electrons (10 events each) generated with phi = PI/4 and eta = 2 (-2 for EEMC). Mean hit tower position and generated particle direction now match for all forward calorimeters.

g4envelopes_axes_femc_eemc_fhcal

fhcal_tower_eta_phi_e_10gev_10events_fixeta_fixphi

femc_tower_eta_phi_e_10gev_10events_fixeta_fixphi

eemc_tower_eta_phi_e_10gev_10events_fixeta_fixphi

**Comment by blackcathj** [comment]
Thanks Nils for the updates. Now this pull request is ready for review ATTN @mccumbermike @pinkenburg 

PS: as an action item from the last software meeting, the timing tag was also added to the raw tower objects in commit c493f4e. This value is not yet filled right now in the tower builder, but I am sure we will find use of it in future data reco and sim.

**Comment by mccumbermike** [comment]
Hello Jin,

I ran the branch with jetty pythia events and the full evaluation and no
errors were reported, so there shouldn't be tracing issues merging this
code.

Mike

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by blackcathj** [comment]
Thanks for confirmation from @mccumbermike and @pinkenburg , merging and testing the final build.

**Pull request merged**
