### PR TITLE
Trackseed refactor

### PR DESCRIPTION
**Pull request by hupereir**
[comment]: <> (Please tell us something about this pull request)
This takes out all non-interface methods from the TrackSeed objects and move them to a helper class TrackSeedHelper.
This allows to have libtrackbase_historic_io link to libtrack_io, instead of libtrack, thus seriously simplifying the library dependencies. 
In addition, this makes versioning of TrackSeed objects much simpler. 
There is a number of TODOs added to the files, where cluster global positions are calculated from acts geometry without accounting for TPC distortion corrections. This was already the case before this change, and should be fixed in a future commit. 

Let's see how this goes ... 

## Types of changes
[comment]: <> ( What types of changes does your code introduce? Put an `x` in all the boxes that apply: )
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work for users)
- [ ] Requiring change in macros repository (Please provide links to the macros pull request in the last section)
- [x] I am a member of [GitHub organization of sPHENIX Collaboration](https://github.com/orgs/sPHENIX-Collaboration/people), EIC, or ECCE (contact Chris Pinkenburg to join)

## What kind of change does this PR introduce? (Bug fix, feature, ...)

[comment]: <> ( What does this PR do? Linking to talk in software meeting encouraged )

## TODOs (if applicable)

[comment]: <> ( In case this is a draft PR, e.g. for running checks using Jenkins, please make the pull request as a draft: https://github.blog/2019-02-14-introducing-draft-pull-requests/  )

### CODE REVIEW

**Comment by hupereir** [comment]
Working on the compilation failure. Some library dependency mess.

**Comment by hupereir** [comment]
Next round of commit. Let's see where this leads us ... 
This is a bit of a butterfly effect.

**Comment by hupereir** [comment]
We'll get there. Just need to build more modules locally and see where it breaks :)

**Comment by hupereir** [comment]
@pinkenburg how can I fetch the change you pushed on my local branch, so that I can keep pushing more changes here ?

**Comment by pinkenburg** [comment]
just do a git pull from within your branch. My commit modified your branch on your fork

**Comment by eumaka** [comment]
hi @hupereir the global vertex map library was there in the original event plane info PR because it was using the vertex for a vertex dependent correction of the event planes. My recent PR removed the corrections due to histogram database storage unavailability. Also the track stuff is there to eventually add event plane determination with low pT tracks

**Comment by eumaka** [comment]
hmm interesting, good luck :)

**Comment by hupereir** [comment]
Marking as draft for the time being: there is apparently a (rare) crash condition in PHSimpleKFProp now, after this change ...
Investigating.

**Comment by hupereir** [comment]
Crash is fixed.

**Review by osbornjd — APPROVED** [review]
Looks good to me, what could go wrong 😄

**Pull request merged**
