### PR TITLE
Calorimeter Digitalization and Calibration

### PR DESCRIPTION
**Pull request by blackcathj**
As discussed in the last simulation meeting, digitalization and calibration modules are introduced. Specific changes are:

## Tower and Tower Builder

RawTowerBuilder now output light yield (previously G4 energy deposition) to DSTNodes of RawTowerv1 objects. RawTowerv1 now support save of a single double precision total energy value, which could be later interpreted as digitized/calibrated value, depending on the DSTNode name.

## Digitalization

RawTowerDigitizer is introduced to convert G4 light yield into digitalized ADC values. Two options supported right now through set_digi_algorithm():
* kNo_digitalization (default for compatibility): directly pass the energy of sim tower to digitalized tower
* kSimple_photon_digitalization: digitalization with Poission photon statistics, ADC conversion and pedstal

## Calibration

RawTowerCalibration further convert ADC value into the measured and calibrated value for use in downstream analysis of clustering and evaluation. Also two options supported right now through set_calib_algorithm():
* kNo_calibration: directly pass the energy of raw tower to calibrated tower. Zero suppression is applied
* simple digitalization with photon statistics, ADC conversion and pedstal

## Reorganize calorimeter related nodes

Now the information flow on the node structure is 
G4CELL_* -> tower ->  TOWER_SIM_* -> digitalization ->  TOWER_RAW_* -> calibration -> TOWER_CALIB_* -> clusterizer -> CLUSTER_*. 
The TOWER_CALIB_* node represents measured value in total energy deposition in GeV, which should be used in downstream analysis of clustering and evaluation. 

Also the DST nodes are organized in PHCompositeNode of the subsystem names 
```
      BBC (PHCompositeNode)/
         BbcVertexMap (PHIODataNode)
      SVTX (PHCompositeNode)/
         G4CELL_SVTX (PHIODataNode)
         SvtxHitMap (PHIODataNode)
         SvtxClusterMap (PHIODataNode)
         SvtxTrackMap (PHIODataNode)
         SvtxVertexMap (PHIODataNode)
      CEMC (PHCompositeNode)/
         G4CELL_CEMC (PHIODataNode)
         TOWER_SIM_CEMC (PHIODataNode)
         TOWER_RAW_CEMC (PHIODataNode)
         TOWER_CALIB_CEMC (PHIODataNode)
         CLUSTER_CEMC (PHIODataNode)
      HCALIN (PHCompositeNode)/
         G4CELL_HCALIN (PHIODataNode)
         TOWER_SIM_HCALIN (PHIODataNode)
         TOWER_RAW_HCALIN (PHIODataNode)
         TOWER_CALIB_HCALIN (PHIODataNode)
         CLUSTER_HCALIN (PHIODataNode)
      HCALOUT (PHCompositeNode)/
         G4CELL_HCALOUT (PHIODataNode)
         TOWER_SIM_HCALOUT (PHIODataNode)
         TOWER_RAW_HCALOUT (PHIODataNode)
         TOWER_CALIB_HCALOUT (PHIODataNode)
         CLUSTER_HCALOUT (PHIODataNode)
```

## Update on evaluator

Since pedstal is introduced to digitized and calibrated towers, cluster and tower evaluator are updated to support Towers with no association to truth particle (i.e. energy from pedstal fluctuation). In that case, truth energy is saved as NAN. 

## How to proceed

I used my private build to make energy resolution plots. So most bugs should be hashed out. Nevertheless, I will appreciate crosschecks. 

If @mccumbermike , @sen1 and @pinkenburg  think this approach is fine, then I can 
1. merge it 
2. kick off a build
3. merge a related pull request in the macro repository  (https://github.com/sPHENIX-Collaboration/macros/pull/4)

### CODE REVIEW

**Comment by pinkenburg** [comment]
It looks good to me. I need to work on the inner hcal and therefore will merge this now.

**Comment by mccumbermike** [comment]
Also seems sensible to me, but I may have some questions at the meeting
tomorrow.

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by mccumbermike** [comment]
Jin I think you should also merge your macro changes.

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by pinkenburg** [comment]
I did that just now - I just waited for the build to be done

On 09/14/2015 12:24 PM, Michael P. McCumber wrote:
> Jin I think you should also merge your macro changes.
>
> --
> Michael P. McCumber, PhD
> Los Alamos National Laboratory
> 505-709-8161
>
> On Mon, Sep 14, 2015 at 10:22 AM, Michael P. McCumber <mccumber@bnl.gov>
> wrote:
>
> > Also seems sensible to me, but I may have some questions at the meeting
> > tomorrow.
> >
> > --
> > Michael P. McCumber, PhD
> > Los Alamos National Laboratory
> > 505-709-8161
> >
> > On Mon, Sep 14, 2015 at 10:12 AM, pinkenburg <notifications@github.com>
> > wrote:
> >
> >> Merged #41
> >> <https://github.com/sPHENIX-Collaboration/coresoftware/pull/41>.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/sPHENIX-Collaboration/coresoftware/pull/41#event-408844735>
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sPHENIX-Collaboration/coresoftware/pull/41#issuecomment-140132852>.
>


-- 

*********************************************************

Christopher H. Pinkenburg      ; pinkenburg@bnl.gov

Brookhaven National Laboratory ; phone: (631) 344-5692
Physics Department Bldg 510 C  ; fax:   (631) 344-3253
Upton, NY 11973-5000

http://www.phenix.bnl.gov/~pinkenbu/

*********************************************************

**Pull request merged**
